package application;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

public class MainController implements Initializable {
	
	@FXML
	public Label myLabel;
	@FXML
	public ComboBox<String> term, degree, subject, 
						 	campus, partOfTerm,
							instructor, type, startHr,
							startMin, startP, endHr,
							endMin, endP;
	
	public TextField courseNum, title, credFrom, credTo;
	
	ObservableList<String> termList = FXCollections.observableArrayList(
			"Spring Semester 2018", 
			"Fall Semester 2017 (View only)", 
			"Summer Semester 2017 (View only)", 
			"Spring Semester 2017 (View only)",
			"Fall Semester 2016 (View only)", 
			"Summer Semester 2016 (View only)", 
			"Spring Semester 2016 (View only)",
			"Fall Semester 2015 (View only)", 
			"Summer Semester 2015 (View only)", 
			"Spring Semester 2015 (View only)",
			"Fall Semester 2014 (View only)", 
			"Summer Semester 2014 (View only)", 
			"Spring Semester 2014 (View only)",
			"Fall Semester 2013 (View only)", 
			"Summer Semester 2013 (View only)", 
			"Spring Semester 2013 (View only)",
			"Fall Semester 2012 (View only)", 
			"Summer Semester 2012 (View only)", 
			"Spring Semester 2012 (View only)",
			"Fall Semester 2011 (View only)", 
			"Summer Semester 2011 (View only)", 
			"Spring Semester 2011 (View only)",
			"Fall Semester 2010 (View only)", 
			"Summer Semester 2010 (View only)", 
			"Spring Semester 2010 (View only)",
			"Fall Semester 2009 (View only)", 
			"Summer Semester 2009 (View only)", 
			"Spring Semester 2009 (View only)",
			"Fall Semester 2008 (View only)", 
			"Summer Semester 2008 (View only)", 
			"Spring Semester 2008 (View only)",
			"Fall Semester 2007 (View only)", 
			"Summer Semester 2007 (View only)", 
			"Spring Semester 2007 (View only)",
			"Fall Semester 2006 (View only)", 
			"Summer Semester 2006 (View only)", 
			"Spring Semester 2006 (View only)",
			"Fall Semester 2005 (View only)", 
			"Summer Semester 2005 (View only)", 
			"Spring Semester 2005 (View only)",
			"Fall Semester 2004 (View only)", 
			"Summer Semester 2004 (View only)", 
			"Spring Semester 2004 (View only)",
			"Fall Semester 2003 (View only)", 
			"Summer Semester 2003 (View only)", 
			"Spring Semester 2003 (View only)",
			"Fall Semester 2002 (View only)");
	ObservableList<String> degList = FXCollections.observableArrayList(
			"Associates (2-year undergraduate, Perimeter College students)", 
			"Bachelors (4-year undergraduate students)", 
			"Graduate (Graduate level students)", 
			"Law (Graduate, College of Law students)");
	ObservableList<String> subList = FXCollections.observableArrayList(
			"ACCOUNTING",
			"ACTUARIAL SCIENCE",
			"AFRICAN-AMERICAN STUDIES",
			"AMERICAN SIGN LANGUAGE",
			"ANALYTICS",
			"ANTHROPOLOGY",
			"APPLIED BASS",
			"APPLIED BASSOON",
			"APPLIED CELLO",
			"APPLIED CLARINET",
			"APPLIED COMPOSITION",
			"APPLIED CONDUCTING",
			"APPLIED EUPHONIUM",
			"APPLIED FLUTE",
			"APPLIED GUITAR",
			"APPLIED HARP",
			"APPLIED HORN",
			"APPLIED JAZZ BASS",
			"APPLIED JAZZ GUITAR",
			"APPLIED LINGUISTICS",
			"APPLIED OBOE",
			"APPLIED ORGAN",
			"APPLIED PERCUSSION",
			"APPLIED PIANO",
			"APPLIED PIANO JAZZ PIANO",
			"APPLIED SAXOPHONE",
			"APPLIED TROMBONE",
			"APPLIED TRUMPET",
			"APPLIED TUBA",
			"APPLIED VIOLA",
			"APPLIED VIOLIN",
			"APPLIED VOICE",
			"ARABIC",
			"ART",
			"ART EDUCATION",
			"ART HISTORY",
			"ASTRONOMY",
			"BIOLOGY",
			"BIOMEDICAL SCIENCE",
			"BIRTH THROUGH FIVE",
			"BUSINESS ADMINISTRATION--BA",
			"BUSINESS ADMINISTRATION--BUSA",
			"BUSINESS COMMUNICATION",
			"CENTER PROCESS INNOVATION",
			"CERAMICS",
			"CHEMISTRY",
			"CHINESE",
			"COMMUNICATION",
			"COMMUNICATION SCI & DISORDERS",
			"COMPUTER INFORMATION SYSTEMS",
			"COMPUTER SCIENCE",
			"COOPERATIVE EDUCATION",
			"COUNSELING & PSYCH SERVICES",
			"CREATIVE MEDIA INDUSTRY STUDY",
			"CRIMINAL JUSTICE",
			"CURRICULUM & INSTRUCTION",
			"DENTAL HYGIENE",
			"DRAWING AND PAINTING",
			"DRAWING, PAINTING, PRINTMAKING",
			"EARLY CHILDHOOD EDUCATION",
			"ECONOMICS",
			"ED, BUSINESS, AND TECHNOLOGY",
			"EDUCATION",
			"EDUCATIONAL POLICY STUDIES",
			"EDUCATIONAL PSYCHOLOGY",
			"ENGINEERING",
			"ENGLISH",
			"ENGLISH AS A SECOND LANG (UG)",
			"ENGLISH SECOND LANGUAGE (GRAD)",
			"ENTREPRENEURSHIP",
			"ENVIRONMENTAL STUDIES",
			"EPS/EDUCATIONAL LEADERSHIP",
			"EPS/RESEARCH",
			"EPS/SOCIAL FOUNDATIONS",
			"EUROPEAN UNION STUDIES",
			"EXCEPTIONAL CHILDREN",
			"EXEC DOCTORATE IN BUSINESS",
			"EXECUTIVE MBA",
			"FILM AND MEDIA",
			"FINANCE",
			"FOREIGN LANGUAGE",
			"FRENCH",
			"GEOGRAPHY",
			"GEOLOGY",
			"GEOSCIENCES",
			"GERMAN",
			"GERONTOLOGY",
			"GLOBAL STUDIES",
			"GRAPHIC DESIGN",
			"GSU NEW STUDENT ORIENTATION",
			"HEALTH ADMINISTRATION",
			"HEBREW - MODERN",
			"HISTORY",
			"HOMELAND SECURITY & EMERG MGMT",
			"HONORS",
			"HOSPITALITY ADMINISTRATION",
			"HUMANITIES",
			"INTEGRATED SCIENCES",
			"INTENSIVE ENGLISH PROGRAM",
			"INTERIOR DESIGN",
			"INTERNATIONAL BUSINESS",
			"INTERNATIONAL EXCHANGE",
			"ITALIAN",
			"JAPANESE",
			"JEWISH STUDIES",
			"JOURNALISM",
			"KINESIOLOGY & HEALTH",
			"KOREAN",
			"LANGUAGE ARTS EDUCATION",
			"LATIN",
			"LAW",
			"LEARNING TECHNOLOGIES",
			"LEGAL STUDIES",
			"MANAGERIAL SCIENCES",
			"MARKETING",
			"MASTER OF BUSINESS ADMIN",
			"MATHEMATICAL RISK MANAGEMENT",
			"MATHEMATICS",
			"MATHEMATICS EDUCATION",
			"MIDDLE EAST STUDIES",
			"MILITARY SCIENCE LEADERSHIP",
			"MUSIC",
			"MUSIC APPRECIATION",
			"MUSIC TECHNOLOGY MANAGEMENT",
			"NATURAL SCIENCES",
			"NEUROSCIENCE",
			"NURSING",
			"NUTRITION",
			"OCCUPATIONAL THERAPY",
			"PERIMETER COLLEGE ORIENTATION",
			"PERSPECTIVES",
			"PHILOSOPHY",
			"PHOTOGRAPHY",
			"PHYSICAL EDUCATION",
			"PHYSICAL THERAPY",
			"PHYSICS",
			"POLITICAL SCIENCE",
			"PORTUGUESE",
			"PRINTMAKING",
			"PROFESSIONAL MASTER BUS ADMIN",
			"PSYCHOLOGY",
			"PUBLIC HEALTH",
			"PUBLIC MANAGEMENT POLICY",
			"READING EDUCATION",
			"REAL ESTATE",
			"RELIGIOUS STUDIES",
			"RESEARCH STRATEGIES",
			"RESPIRATORY THERAPY",
			"RISK MANAGEMENT AND INSURANCE",
			"RUSSIAN",
			"SCH OF NURSING & HEALTH PROF.",
			"SCIENCE EDUCATION",
			"SCULPTURE",
			"SIGN LANGUAGE INTERPRETING",
			"SOCIAL STUDIES EDUCATION",
			"SOCIAL WORK",
			"SOCIOLOGY",
			"SPANISH",
			"SPEECH COMMUNICATION",
			"STATISTICS",
			"SWAHILI",
			"TAXATION",
			"TEACHING ESL/COLLEGE OF ED",
			"TEXTILES",
			"THEATRE",
			"THREE-DIMENSIONAL STUDIES",
			"WOMEN'S GENDER & SEXUALITY STU");
	ObservableList<String> campList = FXCollections.observableArrayList(
			"Alpharetta -Associates courses", 
			"Atlanta", 
			"Clarkston -Associates courses", 
			"Decatur -Associates courses",
			"Distance/Online Learning",
			"Dunwoody -Associates courses",
			"Foreign Campus",
			"Newton -Associates courses",
			"Off Campus-Tech & USG Fee only",
			"Off-Campus with Mand. Fees",
			"Other Uni Sys GA Institution",
			"Study Abroad");
	ObservableList<String> partList = FXCollections.observableArrayList(
			"Exception (All Terms)",
			"Full Term (Fall or Spring)",
			"Mini-mester 1 (Fall or Spring)",
			"Mini-mester 2 (Fall or Spring)");
	ObservableList<String> instList = FXCollections.observableArrayList("All",
			"Aamer, Nadiyah ",
			"Abalmazova, Yelena ",
			"Abbott, Emory Reginald",
			"Abbott, Laura Anne",
			"Abdelaziz, Sarah ",
			"Abdus-Saboor, Kinda ",
			"Abebe, Gebeyehu ",
			"Abrahao, Thalita Balsamo",
			"Abron, Clara Elizabeth",
			"Acharya, Ananta Raj",
			"Acosta, Katie Linette",
			"Adams, Ellis Adjei",
			"Adams, Francis Scott",
			"Adams, Marcus Paul",
			"Adams, M Hiuko Ngari",
			"Adams, Nicholas L",
			"Adams, Teresa B",
			"Adams, Windsor ",
			"Adamson, Andrew N",
			"Adamson, Lauren B.",
			"Addie, Jean-Paul David",
			"Adebayo, Modupeola Motayo",
			"Adesesan, Olufunmilayo A.",
			"Afield, Walter Edward",
			"Aghasi, Alireza ",
			"Aharoni, Eyal ",
			"Ahnert, Laurel E",
			"Ahuja, Tarushee ",
			"Ainsworth, James ",
			"Akbas, Erol ",
			"Akcin, Haci Mustafa",
			"Akimova, Irina ",
			"Akinyela, Makungu M.",
			"Akossi, Aurelie Albertine Logboschi ",
			"Alabdullah, Rasha Abdulmunem Azeez",
			"Albers, H. Elliott",
			"Albers, Margaret M.",
			"Albin, Edward ",
			"Albo, Francisco Javier",
			"Alderson, Robert J",
			"Aleck II, Nimer Isaac",
			"Alembik, Lisa D.",
			"Alemdjrodo, Kangni ",
			"Alexander, Margo Pamela",
			"Alexander, Valerie Jean",
			"Allen, Deatrice Lin",
			"Allen, Derek Bower",
			"Allen, Julia W",
			"Allen, Sally H.",
			"Almada, Lorenzo Nicolas",
			"Almashikee, Thaer Sabri Yasg",
			"Altabe, Madeline Nissa",
			"Altman, Andrew ",
			"Altman, Daniel William",
			"Alvarez, Luis Roberto",
			"Alvarez, Norma L.",
			"Amadi-Ihebuzor, Chidinma A",
			"Amanti, Catherine Bushnell",
			"Ambrose, Robert J.",
			"Ambrose, Sarah Kruser",
			"Ambrosino, Audrey Marie",
			"Ames-Sikora, Alyssa Maureen",
			"Amin, Kinnari Vaibhavkumar",
			"An, Yi-Sen ",
			"Anand, Ankit ",
			"Anderson, Caroline M.",
			"Anderson, Courtney Lauren",
			"Anderson, Ebony Dashawn",
			"Anderson, Jose Luis",
			"Anderson, Morgan Del Vecchio",
			"Anderson, Page L.",
			"Anderson, Thomas J",
			"Andrus, Brice C.",
			"Aneja, Ritu ",
			"Angay-Crowder, Tuba ",
			"Angryk, Rafal Aleksander",
			"Anlicker, Christine Demarest",
			"Ansari, Forough S",
			"Apalkov, Vadym M",
			"Appert, Maryann Baiocco",
			"Aquilo, Nancy Dunning",
			"Arancibia, Jose ",
			"Arav, Marina ",
			"Arcement, Rashad ",
			"Ari, Omer ",
			"Aria, Andrea ",
			"Arikoski-Johnson, Darien Oliver",
			"Armistead, Lisa P.",
			"Armstrong-Mensah, Elizabeth Afibah",
			"Arnold, Deborah Jones",
			"Arnold, Shari Lakia",
			"Arons, Sandrine M.",
			"Arrington, Paige Davis",
			"Artinian, Liana ",
			"Artrip, Aaron C",
			"Asalami, Shadi Ashjaei",
			"Asare-Nkansah, Ernest ",
			"Asfaw, Tesfaye Negash",
			"Ashby, Jeffrey S.",
			"Ashmore, Larry E.",
			"Ashok, Ashwin ",
			"Ashraf, Rasha ",
			"Asiedu, Eddy Darko",
			"Aslam, Mohammad ",
			"Aslan, Hadiye ",
			"Atchison, Kristin ",
			"Athanasios, Shawn Addison",
			"Atkins, Frederick Clarke",
			"Atkinson, Jaynette L.",
			"Attanasio, Roberta ",
			"Atteya, Maher ",
			"Augustine-Gartrell, Dorothy Renee",
			"Aull, Jacob J.",
			"Austin, Garrett Wesley",
			"Austin, Joseph ",
			"Avart, Christian ",
			"Aycock, Dawn Maree",
			"Ayer, Tugba ",
			"Azimi, Andia Minoo",
			"Babaie, Hassan Ali",
			"Bagherieh, Said ",
			"Bagley, Joseph ",
			"Bah, Boubacar ",
			"Bailey, William Harrison",
			"Baird, Aaron ",
			"Baker, Alicia Rose",
			"Baker, Howard Robert",
			"Baker, Jan N.",
			"Baldwin Mason, Greta ",
			"Bales, Carol Jane",
			"Bales, Kevin Sean",
			"Balint, Brendan J",
			"Ballard, Ellen Paige",
			"Ballero, Deniz Zubeyde Altin",
			"Bamunu Mudiyanselage, Thosini Kumarika",
			"Banas, Mark E",
			"Banda, Juan ",
			"Banihashemi, Javad ",
			"Banzhaf, Henry Spencer",
			"Baosman, Ahmed Abdullah",
			"Baptiste, Denise Patricia",
			"Barattin, Anna ",
			"Barazesh, Reza ",
			"Barbaree, Tracey Tatum",
			"Barba Valdivieso, Pamela Estefania",
			"Barber, Diana S",
			"Bardie-Kapaun, Marilyn L",
			"Barker, Jennifer Marilynn",
			"Barker, Rochelle A.",
			"Barksdale, Hiram C.",
			"Barnes, Ava Ward",
			"Barnes, Jennifer Louise",
			"Baro, Deborah J.",
			"Baron, Fabien Robert",
			"Barouch, Timothy Michael",
			"Barr, Pamela ",
			"Barrera, Jason Joe",
			"Barrow, Doyle James",
			"Barrow, Karamo BS",
			"Barth, Claire Rauschenberg",
			"Barthlow, Douglas A.",
			"Barton, Jamila K",
			"Barzegar, Abbas ",
			"Barzegar, Amir H",
			"Bascomb, Lia ",
			"Basenberg, Lanier Frances",
			"Baskerville, Richard L.",
			"Basler, Christopher F.",
			"Bason, James Judd",
			"Bass, Michael Stephen",
			"Bassett, Molly Harbour",
			"Basta, Alfred ",
			"Basta, Nadine ",
			"Batantou, Patrice ",
			"Bateman, Barbara Ann",
			"Bates, Teresa Ann",
			"Battleson, Douglas Aloys",
			"Bauman, Gary Sherman",
			"Baumann, Miranda Lynne",
			"Baumstark, Alfons L.",
			"Baumstark, Barbara R.",
			"Bazemore, Na Keya B  Hardin",
			"Bean, Kayla Irene",
			"Beard, David ",
			"Beard, Tyler E",
			"Beatty, John David",
			"Beauford, William Eugene",
			"Beaumont, James H",
			"Beck, Elizabeth L.",
			"Beck, Theodora Kay",
			"Beckemeyer, Elizabeth Frances",
			"Beckford, Garfield Kenroy",
			"Beirne, Mark J.",
			"Belcher, Diane D",
			"Belcher, Robert Lee",
			"Beldeanu, Ioana ",
			"Belkasim, Saeid ",
			"Bell, David M.",
			"Bello, Daniel C.",
			"Bellon, Joe ",
			"Bellon, Karen E",
			"Belykh, Igor ",
			"Bennafield, Marci ",
			"Bennekin, Kimberly N",
			"Benner, Nicole Elizabeth",
			"Bennett, Alana E.",
			"Bennett, Kim W",
			"Bennett, Kinterri Deyanna",
			"Bennett, Nathan ",
			"Benning, Jeremiah V.",
			"Benson, Charlese Garnett",
			"Benson, Gwendolyn Traylor",
			"Benton, James Edward",
			"Bentz, Misty Cherie",
			"Beran, Michael James",
			"Berens, Debra Ehlers",
			"Berg, Louis-Alexandre ",
			"Berger, Brian Scott",
			"Bermingham, Suji K",
			"Bermudez, Maria E.",
			"Bernal, Carmen L.",
			"Bernard III, Albert Joseph",
			"Berry, Jessica Noelle",
			"Berwick, Amy Courtenay",
			"Besalyan, Raffi ",
			"Bethea, Brittaney Jewel",
			"Bettis, Annette ",
			"Bhachech, Micah D",
			"Bhada, Neville Yezdi",
			"Bhatnagar, Ruchi ",
			"Bhatt, Rachana Ramesh",
			"Bhola, Jaman L.",
			"Bialo, Jacquelyn Anne",
			"Bidwell, Carla Rebecca",
			"Binder, Perry Z.",
			"Bingham, Gary Eldon",
			"Bingley, Matthew A",
			"Black, Denise Ratliff",
			"Black, Michael P.",
			"Black, Steven Patrick",
			"Blackmon, Richard D",
			"Blair, Samantha Kaj",
			"Blake, Janice Gayle",
			"Blakely, Malika Aisha",
			"Blalock, Emily Lauren",
			"Blaustein, David N.",
			"Blinkhorn, Jessica Elaine",
			"Bliss, Lisa Radtke",
			"Block, Michelle N",
			"Bloom, Mia M",
			"Blum, Janna Karen",
			"Boden, Lauren Jordan",
			"Bodnar, Mark Stephen",
			"Boers, Jacobus Francois",
			"Bogner, William C.",
			"Bohan, Chara Haeussler",
			"Bolding, Gladys F.",
			"Bolia, Ly ",
			"Bolsen, Toby W",
			"Bombard, Jason Tyler",
			"Bond, Alesha Deanna",
			"Bondarenko, Vladimir Y",
			"Bonin, Brian Paul",
			"Bonner, Karen Ratigan",
			"Bonner, Nora Jean",
			"Bonnette, Lakeyta Monique",
			"Bonny, Ronald ",
			"Boo, Soyoung ",
			"Boodraj, Maheshwar ",
			"Boone, Mary Amanda",
			"Boortz, Jeffrey Allen",
			"Borek, Lois B.",
			"Borthick, A. Faye",
			"Bost, Lynne Louise",
			"Bostian, April Christine Lynn",
			"Bottoms, David Harold",
			"Bouker, Polly A",
			"Boulamatsi, Artemis ",
			"Boulenger, Celine ",
			"Bourgeois, Anu Goel",
			"Bowen, Abigail C",
			"Bowen, Linda Kathleen",
			"Bowles, Martha S",
			"Bowman, Lorenzo ",
			"Bowman, Sara Elizabeth",
			"Box, Cynthia E.",
			"Boyd, Damita Janeen",
			"Boyd, Jonathan R",
			"Boyd, Kamela Faye",
			"Boyd, Megan Elizabeth",
			"Boyles, Deron Robert",
			"Bradley, Michael T.",
			"Bramblett, Matthew Tolleson",
			"Brandenberger, Kyle Jason",
			"Brandon, Leslie J.",
			"Branscome, David Nathaniel",
			"Brattain, Michelle ",
			"Breaux, Chandra French",
			"Breedlove, Anita Lynn Kite",
			"Breitling, Hansen Garlington",
			"Brennan, Carolyn Louise",
			"Breslin, Paul ",
			"Breslin, Susan ",
			"Brewer, Cassady Vaughn",
			"Brewer, Matthew W.",
			"Brezicha, Kristina F.",
			"Brezina, Timothy J.",
			"Brickman, Jeffrey H.",
			"Bride, Brian ",
			"Bridges-Rhoads, Sarah Catherine",
			"Bright, Nancy Mensah",
			"Brinton, Margo A.",
			"Broadwell, Wendell S.",
			"Brooks, Amber Nicole",
			"Brooks, Angela Susan",
			"Brooks, Fred P.",
			"Brooks, Jody Elizabeth",
			"Brosnan, Sarah Frances",
			"Brothen, Rolf Thorval",
			"Brotherton, Timothy H",
			"Brown, Carrie Wallace",
			"Brown, Christopher ",
			"Brown, Genna ",
			"Brown, Jessica Rogers",
			"Brown, Joseph E.",
			"Brown, Joyce D",
			"Brown, Keisha Michelle Lanier",
			"Brown, Kristin Marie",
			"Brown, Murray Lee",
			"Brown, Ronnie Lamar",
			"Brown, Shawanda Michelle",
			"Brown, Timothy Andrew",
			"Brown, Valerie Ann",
			"Bruce, James Henry",
			"Bruce, Philip Shane",
			"Bryan, Elaine Doris",
			"Bubacz, Eric Charles",
			"Buchman, Emily ",
			"Bulger, Daniel ",
			"Bullard, Sharon Keiano",
			"Buls, Fredrik J",
			"Bumgarner, Lon Edward",
			"Bunch, Kay J.",
			"Bunting, John David",
			"Buras, Kristen L.",
			"Burgess, Elisabeth O.",
			"Burkart, Maureen F",
			"Burnet, Jennie Elizabeth",
			"Burns, Janet L.",
			"Burns, Robert Jonathan",
			"Burrow, Vicki L",
			"Burrus, Cynthia Ann",
			"Burton, Sylvester ",
			"Busbee, Howard J",
			"Buteau, Emmanuel ",
			"Butler, Andrew John",
			"Butler, Deborah A.",
			"Butler, Katherine M",
			"Butler, Margaret Elizabeth",
			"Butts, Terynce ",
			"Buysman, Loren Vern",
			"Byrd, Deborah N",
			"Byrom, Brittny Michelle",
			"Byron, Kristin Lynn",
			"Bytof, Lindsay Marie",
			"Cabrices, Desiree Marie",
			"Cai, Zhipeng ",
			"Cain, Lynda Patricia",
			"Cain, Mary Spencer",
			"Cain, Michael D",
			"Caison, Gina Marie",
			"Calandra, Brendan Dominick",
			"Caldas, Jessica Ruth",
			"Caldwell, Tanya ",
			"Caley, Sylvia B.",
			"Calico, Marla A",
			"Callaghan, Sarah ",
			"Callaway, Janice Lynn",
			"Calvin, Olivia Louise",
			"Camacho, Alison Lynn",
			"Cameron, Marie LouiseWathingto",
			"Campagna, Chris ",
			"Campbell, Candice J McCloskey",
			"Campbell, Ian D",
			"Campbell, Tedric D",
			"Campfield, Alan ",
			"Canada-Egwim, Anita Jo",
			"Canganelli, Teresa A",
			"Cannon, Debra Franklin",
			"Cannon, Joseph A",
			"Cannon, Susan Ophelia",
			"Cannon, Virginetti Smith",
			"Canter, William Harry Yancey",
			"Cantrell, Owen Charles",
			"Cao, Xiaojun ",
			"Cao, Yan ",
			"Capers, Kaisheka Juree",
			"Caras, John Gus",
			"Cardon, Beth Buckingham",
			"Cardon, Clement ",
			"Carey, Hala Linda",
			"Carey, Henry Frank",
			"Carley, Amelia Henrietta",
			"Carlin, Ryan Edward",
			"Carlson, Sarah Elizabeth",
			"Carman, Catherine ",
			"Caro-Hernandez, Brennda ",
			"Carr, Kathleen M",
			"Carrillo, Pedro E.",
			"Carrion, Carmen A",
			"Carroll, Thomas Paul",
			"Carruth, Laura L.",
			"Carter, Joel Devyn",
			"Carter, Laura C.",
			"Carter, Marva Griffin",
			"Carter, Patricia Ann",
			"Carter, Sarah E",
			"Carver, Curtis A",
			"Carver, Julie Shea",
			"Casanova, Jason Jonathan",
			"Casares, Maria Carolina ",
			"Casey, Douglas Marvin",
			"Cash, Annette ",
			"Casimir-Thompson, Cheryl Donnah",
			"Cason, Gary Carlton",
			"Cassaniti, Amy R",
			"Casteel, Cari Leighanne",
			"Castillo-Ruiz, Alexandra ",
			"Castle, Jennifer Susan",
			"Castro Lopez Vaal, Rodrigo Ivan",
			"Casturi, Narasimha Rao Venkatalakshmi",
			"Cater, Casey Patrick",
			"Cates, Caleb Micah",
			"Caton-Williams, Julianne Marie",
			"Cauley, Helen Marie",
			"Cavusgil, Sharon Leigh",
			"Cepeda Contreras, Sarah Shealy",
			"Chahine, Iman C",
			"Chambers, Charles L",
			"Chambers, Melany Mignonette",
			"Chandler, Beatrice Summer",
			"Chang, Catherine Y.",
			"Chapman, Rebekah Elizabeth",
			"Chapura, Mitchell Edward",
			"Chassaing, Benoit ",
			"Chen, Guangyao ",
			"Chen, Guantao ",
			"Chen, Mark Andrew",
			"Chen, Mei-Lan ",
			"Chen, Ruiyun ",
			"Chen, Yu-Ping ",
			"Cheng, Ta-Tung ",
			"Cheng, Yichen ",
			"Cherenet, Fasil ",
			"Cherney, Kristeen E",
			"Cherniavsky, Fyodor A",
			"Cheshier, David Mark",
			"Chikwanda, Patreck ",
			"Childress, Brandi N",
			"Chilungu, Elizabeth Namisi",
			"Chin, Kuk Jeong",
			"China, Chrystal Renee",
			"Chiovaro, Jennifer G.",
			"Chitescu, Simona Isabella",
			"Chlapowski, Taylor James",
			"Cho, Mikyung ",
			"Choi, Jee Won ",
			"Chong, Alberto E",
			"Chou, Rosalind ",
			"Chowdhury, Ashraful A",
			"Chowell-Puente, Gerardo ",
			"Christie, Edward John",
			"Christodoulopoulou, Angeliki ",
			"Chu, Sung Kim",
			"Church, Erin Lynne",
			"Cianfrone, Beth ",
			"Cino, Jessica G.",
			"Clabaugh, Erik Kenneth",
			"Clapp, Morgan C",
			"Clark, Dionne M",
			"Clark, Jasmine Michelle",
			"Clark, Kris J.",
			"Clark, Megan Lisa",
			"Clark, Virginia Elizabeth",
			"Clarke, Susan E.",
			"Clay, Kelli Suzanne",
			"Cleaves, Urban ",
			"Clegg, Kimberly ",
			"Clegg, Mindy Lea",
			"Cleland, Anthony Craig",
			"Clement, Richard Alan",
			"Clements, Emory Lamar",
			"Cleveland, Kimberly Laura",
			"Clevinger, Amanda Marie",
			"Cobb-Walgren, Cathy J.",
			"Cody, Susan Ruth",
			"Cohen, Andrew I.",
			"Cohen, Andrew Jason",
			"Cohen, Blair Joy",
			"Cohen, Gregory Scott",
			"Cohen, Jonathan David",
			"Cohen, Lindsey Lewis",
			"Cohen, Rachelle J",
			"Colatosti, Jennifer M",
			"Coleman, Amy Rochelle",
			"Coleman, Anne-Marie Lydie",
			"Coleman, Jeffrey Kimar",
			"Coleman, W. Dwight",
			"Collier, Asa L",
			"Collins, Carl Brennan",
			"Conde Pedroso, Pablo Rafael",
			"Conklin, Thomas Arthur",
			"Connally, Illiad P.",
			"Conner, Robin Suzanne",
			"Connors, David Michael",
			"Connors, Megan Elizabeth",
			"Constable, Debora D",
			"Conway, Christopher Michael",
			"Cook, Amy Larson",
			"Cook, LaRue ",
			"Cook, Sarah L.",
			"Cook, Wayne A.",
			"Cooper, Rockefeller ",
			"Cooper, Vanessa N.",
			"Cormier, Jacque-Corey ",
			"Corner, Alexander James",
			"Correa, Jorge Ivan",
			"Correro, Nancy Margaret",
			"Cortes, Jose A",
			"Cortes, Viviana S",
			"Corthell, Kimere ",
			"Cosguner, Koray ",
			"Cossar, John Harper",
			"Costello, Jan Robin",
			"Coty, Lawrence Mark",
			"Couch, Kelli Shea",
			"Courtemanche, Charles ",
			"Covey, Russell Dean",
			"Cowan, Elizabeth A",
			"Cox, Christopher Michael",
			"Cox, Daniel Neely",
			"Cox, Edward Thomas",
			"Cox, James C.",
			"Cox, James Marion",
			"Cox, Karen Eugenia",
			"Cox, Rosemary D.",
			"Cox, Samuel H.",
			"Craig, Alan Thomas",
			"Cranford, Kelly Benton",
			"Cranwell-Bruce, Lisa A.",
			"Cremer, Thomas G",
			"Crenshaw, Daniel Michael",
			"Crescenzo, Daniel L",
			"Crespo, Lisbelle Surama",
			"Crew, Caroline Mary Howden",
			"Crichlow, Vena Ruby",
			"Crimmins, Timothy ",
			"Crisp, April Babb",
			"Crisp, Thomas Bryan",
			"Crooks, Ryan Henderson",
			"Cross, Marcia Jones",
			"Crossley, Scott Andrew",
			"Crowell McQuarrie, Susanna Jane",
			"Crowe-Taylor, Mary Alice",
			"Crowther, Kathryn Elizabeth",
			"Cruz, Francisco ",
			"Cubukcu Can, Feryal ",
			"Cui, Jianmei ",
			"Culpepper, N. Brandt ",
			"Cummings, Alexander Sayf",
			"Cunningham, Clark D.",
			"Cunningham, Katherine Erin",
			"Curasi, Carolyn F.",
			"Curcio, Andrea A.",
			"Curlette, William L.",
			"Curry, Kristina Elaine",
			"Curry IV, Mack ",
			"Curtis, Kelly Ann",
			"Curtis, Philip Kerry",
			"Curtright, Lauren Catherine",
			"Cushenan, Pamela Oreto",
			"Cushing, Sara T.",
			"Custer, William S.",
			"Cymbalyuk, Gennady S",
			"Dabney, Dean ",
			"Dadzie, Kofi Q.",
			"Dahl, Lara Saville",
			"Dai, Dajun ",
			"Dakhli, Mourad ",
			"Dallow, Joel Aaron",
			"Damarin, Amanda K",
			"Damico, John Kelly",
			"Dammers, Kim S.",
			"D'Andrea, Anna Lee",
			"Daniels, Jennifer P.",
			"D'Anjou-Turner, Tamara-Louise Aziza",
			"Darden, Tanja Rachelle",
			"D'Arienzo, Meredith H",
			"Da Rosa, Grace Dorea ",
			"Darragh, Joy Susan",
			"Darrisaw, Amos Renzel",
			"Darrow, Susannah Britton",
			"Darsey, James F.",
			"Darvishzadeh, Navid ",
			"Davarpanah, Armita ",
			"Davenport, April Shanene",
			"Davenport, Melanie G.",
			"Davidson, Denise Z.",
			"Davidson, Wendy Cheryl",
			"Davie, Lisa ",
			"Davis, Ashlee S",
			"Davis, Don Emerson",
			"Davis, George William",
			"Davis, Jacqueline Denise",
			"Davis, Janet T.",
			"Davis, Jeffrey W.",
			"Davis, Lisa A",
			"Davis, Marni Ellen",
			"Davis, Patricia Gail",
			"Davis, Sarita Kay",
			"Davis, Shadonna Ieisha",
			"Davis, Tomeka Mamette",
			"Davis, Vincent Ray",
			"Davison, Mary Bethel",
			"Dayananda, Mathes A. Kanishka",
			"Deane, Richard Harold",
			"Deangelis, Matthew David",
			"Dear, Renanda Wood",
			"Deblaere, Cirleen ",
			"De La Brousse, Alain C.",
			"Delhey, Matthew J",
			"de Liniere, Michele J.",
			"Deliu, Anca Liliana",
			"Della Tonia, Vicente ",
			"DelRio Parra, Elena ",
			"Del Valle, Alejandro ",
			"Demars, Laura Eloise",
			"Demir, Kadir ",
			"Demos, Nick J.",
			"Demuyakor, George ",
			"Denkinger, Shelly Ann",
			"Denning, Timothy Luke",
			"Dent-Roseberry, Beverly ",
			"Denzel, Heidi Dorothea",
			"Denzer, Debra Kay",
			"Deocampo, Daniel Michael",
			"Derby, Charles D.",
			"Derby, Sharon Ruth",
			"Desrochers, Robert Ernest",
			"De Vries, Geert ",
			"Dew, Brian Jackson",
			"Dew, Jason M",
			"Dhakal, Dimple Rani",
			"Dhamala, Mukeshwar ",
			"Diaby, Makani ",
			"Diamond, Beryl Isaac",
			"Dibenardo, Andrea Joy",
			"Dickinson, Dennis Joseph",
			"Diebert, Michael S",
			"Diem, Jeremy E.",
			"Dietz, Nikolaus ",
			"DiGioia, Pamela M",
			"Dills, Alan M",
			"Dimitrov, Kalin Valentinov",
			"Dionne, Steven Scott",
			"Disney, Lindsey Ruth",
			"Dispenza, Franco ",
			"Ditmann, Laurent ",
			"Ditzler, Andrew R",
			"Dix, Richard Devane",
			"Dixon, Angela ",
			"Dixon, Dabney White",
			"Dobranski, Stephen B.",
			"Dodds, Priscilla ",
			"Dokter, Julia Rose",
			"Dolan, Kathleen Anne",
			"Dolloff, Matthew K",
			"Doluweera, Doluwarawatta Gamage",
			"Domengeaux, Brandy Owens",
			"Donaldson, Samuel Allen",
			"Donati, Matthew Ryan",
			"Donehower, Claire Lindsay",
			"Dong, Lin ",
			"Dongoski, Craig ",
			"Donnelly, Mary Marguerite",
			"Dopson, Stephanie A.",
			"Doria, Evaristo Fernando",
			"Dotson, Vonetta Michelle",
			"Douberly-Gorman, Rebecca Ann",
			"Downs, William Edward",
			"Doyle, Hannah Elizabeth",
			"Doyle, James Andrew",
			"Drennen, Anthony Craig",
			"Drucker, Michael ",
			"Du, Hong ",
			"Du, Zhenming ",
			"Dube, Shanta R.",
			"Duncan, Anne Susan",
			"Duncan, George E.",
			"Duncan, Jennifer Mcallister",
			"Duncan, Molly Katherine",
			"Dunkley, Nyasha Monique",
			"Dunn, Jay Patrick",
			"Dunn, Jessamine Corey",
			"Dunn, Leslie Ann Lunsford",
			"Dunning, Kenneth Sutton",
			"Dunson, Trudy Faye",
			"Durant, Bettina Benoit",
			"Durden, Tonia Renee",
			"Durham, Erin-Elizabeth Anderson Augard",
			"Durrenberger, Melody R.",
			"Dutta, Antara ",
			"Dwan, Wen-Shing ",
			"Dwyer, Sandra L.",
			"Dyne, Sarah Ann",
			"Eades, Lee H.",
			"Earl, Chantee ",
			"Easton, Whitney Leigh",
			"Eaton, Robert Garcia",
			"Eckert, Lindsey Jane",
			"Edmunds, Laura ",
			"Edmundson, William A.",
			"Edwards, Robert Grant",
			"Edwards, Tiffany Alisa",
			"Edwards, Virgil Lee",
			"Eghbalzad, Leyla ",
			"Eichenbaum, Zehava ",
			"Eidson, Rodger Henry",
			"Eilertson, Carmen D.",
			"Elfakhani, Manal ",
			"Ellen, Pam Scholder",
			"Elliott, Adrian Ashley",
			"Elliott, Patrick Thomas",
			"Elliott, W. Crawford",
			"Ellis, Stephanie Rebecca",
			"Ellwanger, Amanda Leigh",
			"El-Mayas, Hanan Lea",
			"Elsayed, Mahmoud Abduh Ali",
			"Elsberry, Fred Thomas",
			"Emerson, Judith ",
			"Emilio, Gregory A",
			"Enderle, Patrick James",
			"Enescu, Florian ",
			"English, Jacob A.",
			"Engstrom, James D",
			"Enloe, Luther David",
			"Eriksen, Michael P.",
			"Ernst, Rachel Suzanne",
			"Eroglu, Sevgin A.",
			"Esaki, Brett Jonathan",
			"Eskew, Glenn T.",
			"Esposito, Jennifer ",
			"Estrada, Rolando Jose",
			"Etheridge, Patricia Gale",
			"Etsitty, Henry L",
			"Evangelista, Rhiannon ",
			"Evanovich, Lauren ",
			"Evans, John Richard",
			"Evans, Michael Clinton",
			"Evans, Robyn V.",
			"Evans, Zachary Glenn",
			"Fabregat Rodergas, Eduard ",
			"Fairbanks, Bailey R",
			"Falkenberg, Virginia R",
			"Fang, Ning ",
			"Fang, Xiangming ",
			"Fannin, Lauren Denise",
			"Fanoe, Andrew Lawrence",
			"Fareeduddin, Asim ",
			"Farmer, Donna Lane",
			"Farmer, Katherine F",
			"Farnell, Cynthia Carolyn",
			"Farooqui, Sahar ",
			"Farrell, Anne M",
			"Farrell, Bradley ",
			"Farris, John ",
			"Fasihi, Mohammad Obaidullah",
			"Faulkner, Melissa ",
			"Faust, Robert Earl",
			"Fawaz, Dan P",
			"Feinberg, Iris Zeevi",
			"Feinberg, Joseph R.",
			"Feit, Mario Andreas",
			"Feizollahi, Mohammadjavad ",
			"Feldhaus, William R.",
			"Felfli, Zineb ",
			"Feltenstein, Andrew ",
			"Fendler, Richard J.",
			"Feng, Bo ",
			"Fenn, Christopher J.",
			"Fentem, Donald Andrew",
			"Feresin, Rafaela ",
			"Ferguson, Ayanay Camille",
			"Fernandez, Hector D.",
			"Fernandez, Pedro C",
			"Fernando, Nilmi Thushara",
			"Ferreira, Diego Maximiliano",
			"Fesseha, Solomon ",
			"Finan, Regina ",
			"Finazzo, Susan F",
			"Finley, Randy ",
			"Fiore, Rachel Lynn",
			"Firat Hines, Rengin Bahar",
			"Firouzi Naeim, Peyman ",
			"Fischer, Paul Hadwin Keith",
			"Fish, Thomas Ryan",
			"Fisher, Teresa Renae",
			"Fitz-Gerald, Timothy Alton",
			"Fitzpatrick, Stephan David",
			"Fix, Michael Paul",
			"Fjelstul, Kirk Randall",
			"Flato, Jason Marc",
			"Fleming, Anna McCaghren",
			"Flemming, Timothy Michael",
			"Flemons, Stanton Paul",
			"Fletcher, Hosanna Kathryn",
			"Fletcher, Ian C.",
			"Flexner, Paul A.",
			"Florence, Michelle E",
			"Flowers, Gina B.",
			"Flowers, Tiffany Jenine Armstead",
			"Flowers, Timothy R.",
			"Flynn, Robert J",
			"Flynn, Sarah ",
			"Ford, Larkin Henry",
			"Forge, Nicholas A.",
			"Forger, Nancy ",
			"Forquer, David R.",
			"Forsyth, Erin Elizabeth Mcgoff",
			"Fortner, Charles Kevin",
			"Foster, Christopher John",
			"Fournillier, Janice Bernadine",
			"Fowkes, Julie Elizabeth",
			"Fowler, Daren Randall",
			"Fox, Charles Winfred",
			"Fox, Kyle Rashun",
			"Frackenpohl, David ",
			"Francis, Cynthia Elodi",
			"Francis, Gladys M",
			"Francis-Asante, Janie Louise",
			"Franco, Marisa Gina",
			"Frank, Adam M",
			"Frank, Jill Lea",
			"Franklin, Daniel P.",
			"Frantz, Kyle J.",
			"Frazier, John N",
			"Frazier, Lauren Elizabeth",
			"Frederick, Chad H",
			"Freeman, Carrie Packwood",
			"Freeman, Carroll Benton",
			"Freeman, Kay Paschal",
			"Freeney, Sabrina A.",
			"Freer, Patrick K",
			"French-Lee, Stacey Yvonne",
			"Friedman, Edward J.",
			"Friginal, Eric ",
			"Frilingos, Timothy Michael",
			"Frisina, Cynthia L",
			"Frost, Shelby Dawn",
			"Fryfogle, Paul ",
			"Fujioka, Yuki ",
			"Fulk, John E",
			"Fulk, Martha Nega",
			"Fuller, Christina Hemphill",
			"Fuller, Diana M",
			"Fuller, Harcourt Tolstoy",
			"Furey, Hester Leone",
			"Furrow, Howa Beth",
			"Fuse Brown, Erin Chiyoko",
			"Gadda, Giovanni ",
			"Gage, Rachel Lauren",
			"Gaines, Gene Thomas",
			"Galilaias, Christos ",
			"Galindo Parra, Encarnacion ",
			"Gallo, Sergio R.",
			"Galloway, Angus Niall",
			"Gammill, Donald Irving",
			"Garcia, Ebony M",
			"Garcia, Jodan ",
			"Gardenhire, Doug S.",
			"Gardenhire, Robin E.",
			"Gardiner, Richard G",
			"Garfin, Deborah Gail",
			"Garg, Pallavi ",
			"Garner, James Robert",
			"Garofalo, Stephanie Marie",
			"Garrett, Crystal ",
			"Garrigus, Carl E.",
			"Garrison, Jannie Kim",
			"Garver, Jane Foley",
			"Gary, Meta Elizabeth",
			"Gatcombe, Rosalyn R",
			"Gaustad, Paul ",
			"Gautreaux, Ryan J",
			"Gay, Charles Mac",
			"Gay, Gerald D.",
			"Gay, Linda Luckridge",
			"Gay, Pearl Milner",
			"Gay, Shanequa ",
			"Gayles, Jonathan ",
			"Gayman, Mathew D",
			"Gearing, Nicole Venuto",
			"Gebert, Andrew ",
			"Geeter, Andy Patrick",
			"Geil, Mark Daniel",
			"Geil, Sarah Katherine",
			"Geng, Ziyi ",
			"George, Lacy Kay",
			"Gerber, Stuart W.",
			"Germann, Jonathan Edward",
			"Germann, Markus W.",
			"Gershon, Sarah Roberts Allen",
			"Gewirtz, Andrew ",
			"Gibson, John David",
			"Giddings, Tiara L",
			"Gies, Douglas R.",
			"Gilbert, Armida ",
			"Gilbert, Eric Seth",
			"Gilbert, Nancy Ann",
			"Gilbert, Phyllis Marie",
			"Gilbert, Ralph Allan",
			"Gilbride, Dennis David",
			"Gimpel, Gregory Brant",
			"Gindhart, Maria P.",
			"Gipson, Grace Deniece",
			"Girmay, David Berhane",
			"Gissy, William G.",
			"Gittens, Rhana A",
			"Givhan, Kiarra ",
			"Gladfelter, Jamie L",
			"Gladfelter, Laura Anne",
			"Glebova, Olga ",
			"Glover, Ciara Pleshette Smalls",
			"Glover, Jeffrey Barron",
			"Gobron, Louise Marie",
			"Godbey, Jonathan Manley",
			"Godsave, Patricia Ann",
			"Goerger, Benjamin Mcmillen",
			"Gok, Aysegul ",
			"Goldberg, Hanah Rose",
			"Goldberg, Zachary ",
			"Gonzalez Williams, Mercedes ",
			"Goode, Christopher Thomas",
			"Goodfellow, Lynda Thomas",
			"Goodling, Lauri Bohanan",
			"Goodman, Audrey ",
			"Goodman, Stewart Brooks",
			"Goodwin, Brian ",
			"Gordon, Paula Michelle",
			"Gore, Jane B.",
			"Gore, Pamela J W",
			"Goreczny, Ashley Sahar",
			"Goss, Desmond Francis",
			"Gossett, Neeley Ann",
			"Gotlieb, Aaron Franklin",
			"Goulette, Elizabeth Suzanne",
			"Gozem, Samer ",
			"Graham, Gerald Forman Sandaidh",
			"Graham, Thomas E",
			"Grant, Kathryn B.",
			"Grant, Shanah Karen",
			"Grantham, Carol Alice",
			"Grass, Wende Leigh",
			"Graves, Lawrence E",
			"Graves, Mark David",
			"Graves, Stephanie Ann",
			"Gray, Carissa Nicole",
			"Graybeal, Geoffrey Michael",
			"Greathouse, Candice Marie",
			"Green, Anthony Donovan",
			"Green, Laura Elizabeth",
			"Green, Mark Spencer",
			"Greenberg, Jerrold ",
			"Greene, Barbara Jane",
			"Greene, Oliver ",
			"Greenwald, Robert James",
			"Greenwood, Leanna Rose",
			"Greer, Karen L",
			"Gregorzek, Paul Stephen",
			"Grelecki, Ryan Christopher",
			"Griffin, Hope Renee",
			"Griffin, William Lofton",
			"Griggs, Julie Ann",
			"Grimm, Charles C",
			"Grindstaff, Davin ",
			"Grinshpon, Mark Samuilovich",
			"Griswold, Alicia B.",
			"Grober, Matthew S.",
			"Gross, Jade Elise",
			"Grove, John Thomas",
			"Grovenstein, Phillip Brandon",
			"Grubbs, Larry Benjamin",
			"Grubbs, Shelby Russell",
			"Grussendorf, Anke Lydia",
			"Gu, Baotong ",
			"Gu, Lei ",
			"Gu, Qian ",
			"Gu, Wenjun ",
			"Guerreiro-Aires, Mathias H.",
			"Guerrier, Anjelica Ashley",
			"Guinn, James Williams",
			"Gum, Jordan Dallas",
			"Gunhouse, William Glenn",
			"Gunn, JENNY MARIE BEENE",
			"Guo, Qiheng ",
			"Guo, Weiwei ",
			"Gup, Nancy Jane",
			"Gurewicz, Rachel ",
			"Gurmu, Shiferaw ",
			"Guthrie, Jason Lee",
			"Guthrie, Kenneth Ivan",
			"Guvensel, Onurkan ",
			"Guyton, Daniel C",
			"Guyton, William E.",
			"Gylys, Beth A.",
			"Hacker, Joseph Franklyn",
			"Hackett, Jacob Daniel",
			"Hackman, Melissa Joy",
			"Hagan, Andrew Bowie",
			"Haghbaali, Mehdi ",
			"Hai, Yan ",
			"Hall, Barbara Jean",
			"Hall, Barry L",
			"Hall, Douglas M",
			"Hall, Frank J.",
			"Hall, Jennifer Thomson",
			"Hall, Mary S",
			"Hall, Myra Carmen",
			"Hall, Rozaura Vivas",
			"Hall-Godsey, Angela Marie",
			"Hamby, Charlie M.",
			"Hamelberg, Donald ",
			"Hamm, Cynthia Joanne",
			"Hankins, Katherine B.",
			"Hansen, Sarah Grace",
			"Harden, Donald Gregory",
			"Harden, Jeremiah David",
			"Harding, Barbara Anne",
			"Hardt, Greg ",
			"Haring, Christa Dawn",
			"Harker, Michael W.",
			"Harley, Chanel L",
			"Harmon, Molly Ann",
			"Harned, Linda Mclean",
			"Harney, Anna Margaret",
			"Harper, Valerie L.",
			"Harrell, Randall Wayne",
			"Harris, Carol Ann",
			"Harris, Elizabeth ",
			"Harris, Jeremy M",
			"Harrison, Kay Cole",
			"Harrison, Robert Wilson",
			"Harsch, Nicole Michelle",
			"Hart, Lynn Cecilia",
			"Hartel, Heather Anne",
			"Hartgrove, Mary Kathryn",
			"Hartinger-Saunders, Robin Marie",
			"Hartley, Angela Miller",
			"Hartley, Christie J.",
			"Hartley, Jennifer S",
			"Hartman, Victor E.",
			"Hartnell, Chad Allan",
			"Harvey, Penny Margaret",
			"Harvey, Wesley ",
			"Harwood, Grace Sara",
			"Hasenkopf, Barry ",
			"Hasni, Anita Amin",
			"Hassan-Zadeh, Ebrahim ",
			"Hastings, Gary ",
			"Hastings, Laura Anne",
			"Hayat, Matthew Jason",
			"Hayden, Jessie W.",
			"Haydon, Geoffrey J.",
			"Hayes, Katelyn ",
			"Hayes, Stephen Martin",
			"Haynie, Stephanie Dawn",
			"He, Shushan ",
			"He, Xiochun ",
			"Heath, Ryan Scott",
			"Heiman, Harry Jay",
			"Heled, Yaniv ",
			"Helms, James Edward",
			"Helms, Taylor Dwayne",
			"Henary, Maged Mories",
			"Hendricks, Andrea M",
			"Hendricks, Todd A",
			"Hendrix, Richard W",
			"Hendry, John Patrick",
			"Hendry, Terri M.",
			"Henes, Sarah Terese",
			"Henning, Tara Catherine Randolph",
			"Henrich, Christopher C.",
			"Henry, Geoffrey Daniel",
			"Henry, Louis R.",
			"Henry, Todd J.",
			"Hensel, Wendy F.",
			"Henson, Lanier Elsworth",
			"Herb, Michael Frederick",
			"Herbst-Lucke, Stephanie ",
			"Hercules, Jane Midea",
			"Herman, Jonathan R.",
			"Herndon, Ronald Malcolm",
			"Herro, Steven Kenneth",
			"Herron, William C.",
			"Hester, Kristen A.",
			"Heston, Brian P",
			"Heuer, Jennifer ",
			"Heutel, Garth ",
			"Hibbard, Mace Andrew",
			"Hicks, Timothy Alex",
			"Hidalgo, Carlos A",
			"Hidalgo-Odio, Paulo Jose",
			"Higgins, Matthew R",
			"Hildreth, William Bartley",
			"Hill, Heather ",
			"Hill, Kirsten ",
			"Hill, Sharon L.",
			"Hill, Tiffannie Chee",
			"Hilliard, Julia ",
			"Hinerfeld, Deborah ",
			"Hinkle, Joshua Conard",
			"Hires, Kimberly ",
			"Hirsch, Barry T.",
			"Hobson, Maurice ",
			"Hocks, Mary E.",
			"Hoff, Tarryn J.",
			"Hoffman, Chrystina Yong",
			"Hoffman, Dolores M",
			"Hoffner, Cynthia ",
			"Hogan, Charles Eugene",
			"Holland, William Wyatt",
			"Holley, Karen McKinney",
			"Hollibaugh, Casey I",
			"Hollier, Mark John",
			"Holliman, Lenze Ellen",
			"Holloman, Darryl B.",
			"Holman, John W.",
			"Holmes, Ashley Joyce",
			"Holmes, Daniel Brad",
			"Holmes, Shirlene ",
			"Holt, Frances B.",
			"Holtam, Elizabeth Totty",
			"Hong, Jihee ",
			"Hong, Shuguang ",
			"Honkan, Anant G",
			"Hopkins, Barbara Lee",
			"Hopkins, Robert Lee",
			"Hopkins, William Donald",
			"Hopper, Christina Quattrone",
			"Horgan, John Gerard",
			"Horne, Eva Mae",
			"Horton, Justin Bates",
			"Hose, Roxanne Koren",
			"Hosseini, Seyed ",
			"Houchins, David E.",
			"Houghton, John E.",
			"House, Sandee D.",
			"Howard, Rebecca Marie",
			"Howell, Jessica Lauren",
			"Hoyt, Kimberly Yvette",
			"Hsieh, Kevin ",
			"Hsieh, Po-An ",
			"Hu, Xiaolin ",
			"Huang, Jidong ",
			"Huang, Lixin ",
			"Huang, Zhen ",
			"Hudson, Jazmine Rocquel",
			"Hudson, Paul Stephen",
			"Huebschmann, Ray E",
			"Huff, Robin Y.",
			"Huff, William A",
			"Huggins, Carla Friend",
			"Huggins, Summer M",
			"Hughes, Evelyn Michele",
			"Hughes-Isley, Susan ",
			"Huhman, Kim Levy",
			"Humphrey, Tabitha Celeste",
			"Humphreys, Daniel Richard",
			"Hunt, Brian Allen",
			"Hunt, Donald Edward",
			"Hunter, Charles V.",
			"Hunter, Rodney G",
			"Hurst, Eric Demian",
			"Hurst, Steven F",
			"Hurt, James Warren",
			"Hutchinson, Kenneth Leroy",
			"Iannarone, Nicole Gail",
			"Icer, Pelin Burcak",
			"Ignatowicz, Leszek ",
			"Ijuin, Colleen Patricia",
			"Ikaiddi, Anthony Asuquo",
			"Ilgen, Julie Christine",
			"Il'yasova, Dora ",
			"Imarhiagbe, Franklin ",
			"Imbsweiler, Eva Regina",
			"Immergluck, Daniel William",
			"Ingalls, Christopher P.",
			"Irving, Miles Anthony",
			"Irwin, Jacob Paul",
			"Islam, A K M Kamrul ",
			"Israili, Zafar Hasan",
			"Ivanov, Ivaylo ",
			"Ivey, Bridgitte C",
			"Iwaniec, David Mac",
			"Iyer, Suri Saranathan",
			"Jabr, Wael ",
			"Jackson, Angela E",
			"Jackson, Angela Gail",
			"Jackson, Bernice W",
			"Jackson, Hannah Lee",
			"Jackson, Joshua R",
			"Jackson, Leonard Anthony",
			"Jackson, Thomas Patrick",
			"Jackson, Vincent V",
			"Jacobs, Rosalyn Claudette",
			"Jacobs, Tiffany Gale",
			"Jacobson, Stephen R.",
			"Jacques, Scott Thomas",
			"Jain, Shalini ",
			"Jalalitabar, Maryamsadat ",
			"James, Claire Elizabeth-Ellen",
			"Jannot, Jeannine M",
			"Jarek, Allison Lucille",
			"Jarrett, William Jay",
			"Jayne, Patricia Kelley",
			"Jefferies, Stuart Mark",
			"Jenkins, Kyle Joseph",
			"Jenkins, Robin David",
			"Jennings, Brenda H",
			"Jensen, Beth Ann",
			"Ji, Shihao ",
			"Ji, Xiangming ",
			"Jiang, Chun ",
			"Jiang, Jie ",
			"Jiang, Yi ",
			"Jiles, Jennifer D.",
			"Jimenez, Eliseo Dave",
			"Jing, Guangming ",
			"Jo, Beomhee ",
			"John, Douglas L",
			"Johnson, Casonya Matese",
			"Johnson, Cyntoria ",
			"Johnson, Eric V",
			"Johnson, Evan Layne",
			"Johnson, Gwenyth Liewellyn",
			"Johnson, Jessica Davette",
			"Johnson, Ken P",
			"Johnson, Laura Garfield",
			"Johnson, Ouida Williams",
			"Johnson, Sonyja Lania",
			"Johnson, Thaddeus L",
			"Johnson, Timothy H",
			"Johnson, William Gregory",
			"Johnston, Tricia Marie",
			"Johnston, Wesley J.",
			"Joksimovic-Ginn, Bojana ",
			"Jones, Alyse W",
			"Jones, Andrew Michael",
			"Jones, Andrew Thomas",
			"Jones, Ashley P",
			"Jones, Jessica Elizabeth",
			"Jones, Jordan William",
			"Jones, Joy M.",
			"Jones, Karen Lorraine",
			"Jones, Kent Hawley",
			"Jones, Laura Ellen",
			"Jones, Lee Brewer",
			"Jones, Paul Walter",
			"Jones, Steve ",
			"Jones, Veanne Janette",
			"Jones, Yoshana B",
			"Jordan, Laurn Reye",
			"Jordan, Michael Sidney",
			"Joseph, Deanna Lynn",
			"Joseph, Sheri L.",
			"Joyner, Joann Maria Lee",
			"Judson, Robert William",
			"Juergensmeyer, Julian C.",
			"Jung, Soo keung ",
			"Junor-Clarke, Pier Angeli",
			"Jurjevic, Andrea ",
			"Kabengi, Nadine ",
			"Kahrs, James R",
			"Kail, Benjamin Lennox",
			"Kaine, Evan Lyle",
			"Kalisa, Beryl Graham",
			"Kamdar, Pravin C",
			"Kanan, Trisha Kathleen",
			"Kane, Carrie A",
			"Kang, Sang-Moo ",
			"Kappenstein, Annika Olga",
			"Kassorla, Michelle G.",
			"Kasun, Gail Sue",
			"Katz, Paul S.",
			"Katz Crook, Max Travis",
			"Kaufman, Bruce ",
			"Kaufmann, Jodi ",
			"Kaur, Parjit ",
			"Kausar, Auj ",
			"Keddington, Holly B",
			"Keefer, William David",
			"Keehn, Gabriel T",
			"Keel, Sara Dirksen",
			"Keever, Leigh Brittingham",
			"Kegley, Sarah Nkkati",
			"Keil, Mark ",
			"Keith, Susan Fannon",
			"Kellett, Kimberly M",
			"Kelley, Gregory George",
			"Kelley, Melody D",
			"Kellison, Timothy Brandon",
			"Kelly, Joseph Lawson",
			"Kemp, Aubrey Elizabeth",
			"Kemp, William Andrew",
			"Kendrick, Eric Todd",
			"Keniley, Scott Lawrence",
			"Kennedy, Christina Nicole",
			"Kennedy, G. Davon",
			"Kerce, Stephanie Dean",
			"Kerew, Kendall Lynn",
			"Kerlin, Janelle A.",
			"Kerr, Tracy Alexandra",
			"Kershner, Stacie Patrice",
			"Kesner, John Edward",
			"Ketsche, Patricia Gregory",
			"Kharrazi-Wakeman, Minoosh ",
			"Kiage, Lawrence ",
			"Kielly, Archibald James",
			"Kihato, Susan Nyambura",
			"Kile, James C",
			"Killian, Sarah Martin",
			"Kim, Dongjin ",
			"Kim, Hyungmin ",
			"Kim, Jung Ha",
			"Kim, Min Kyu ",
			"Kim, Minkyung ",
			"Kim, Mirae ",
			"Kim, Seiyoun ",
			"Kim, Seongshin ",
			"Kim, Soon-Ho ",
			"Kim, You Jin ",
			"Kimbell, Emily Nicole",
			"King, John David",
			"King, Joyce Elaine",
			"King, Joyce Lynn",
			"King, Laura Leesa",
			"King, Natalie Simone",
			"King, Robert J",
			"King, Tiffany Jeannette",
			"King, Tricia Zawacki",
			"Kini, Omesh ",
			"Kinkopf, Neil J.",
			"Kirk, Richard M",
			"Kirk, Sadler W",
			"Kirkaldy, Debra Jane Luney",
			"Kirkendoll, Kenya Desiree",
			"Kirkland, Katie Lane Wynne",
			"Kirn, Russell Walter",
			"Klausner, Debra E.",
			"Klein, Robert W.",
			"Klein, Sarah Vogt",
			"Klingbeil, Matthew ",
			"Kniazev, Sergei Nikolayevich ",
			"Knighton, Evelyn Ailene",
			"Knowles, Robert Gordon",
			"Kocela, Christopher P",
			"Koch, William John",
			"Koen, Jim Hugh",
			"Koenig, Friederike ",
			"Kolenda, Benjamin Robert",
			"Kolpy, Stephanie Elaine",
			"Konrad, Miriam J.",
			"Koonce, Valarie Jean",
			"Korndoerfer, Jens ",
			"Kossover, Herbert Allan",
			"Kozaitis, Kathryn ",
			"Kozhanov, Alexander ",
			"Krache, Donna R.",
			"Kreisman, Daniel Michael",
			"Kreutzer, Cynthia D",
			"Krinsky, Kim L",
			"Kroeppler, Karl Gustav",
			"Krolak, John Michael",
			"Kruger, Ann C.",
			"Kubala, Juliana M.",
			"Kucelin, Ana Lucija",
			"Kuezi-Nke, Marjorie Chisale",
			"Kulkarni, Abhir ",
			"Kumaresan, Natarajan ",
			"Kummerow Brown, Kiersten ",
			"Kunzelman, Cameron Tyler",
			"Kuperminc, Gabriel P.",
			"Kurumada, Katharine Simon",
			"Kuzio De Naray, Rachel ",
			"Kwon, Hyun-Jin ",
			"Laduke, Bettie ",
			"Lahaise, Diane Marie",
			"Lahaise, Ulrike G",
			"Lahaise, William H",
			"Lake, Ryan N",
			"Lake, William Michael",
			"Lakes, Richard D.",
			"LAMAR, TOSHA ",
			"Lambe, Cormac Sean",
			"Lambert, Lisa S",
			"Lance, Molly Bridgett",
			"Land, Robert William",
			"Landau, Michael B.",
			"Lane, Penelope Dianne",
			"Lane, William A",
			"Lanes, Sasha Tulloch",
			"Langley, Julie J.",
			"Langley, Nickolas Reed",
			"Langston, Stephanie H",
			"La Plant, Kristina Marie",
			"Largent, Sharon Millirons",
			"Laroui, Hamed ",
			"Larsson, Margareta Lena",
			"Lasco, Richard A",
			"Latimer, Shana Lea",
			"Latzman, Robert David",
			"Lauka, Alban ",
			"Laures Gores, Jacqueline Sue",
			"Laury, Susan K.",
			"Laushey, Kelle Mechelle",
			"Lavizzo, Evelyn Aurelia",
			"Law, Jocelyn P.",
			"Law, Kouok K",
			"Law, Michael Patrick",
			"Law, Yvonne ",
			"Lawlor, Leila A.",
			"Lawrence, Benjamin Charles",
			"Lawrence, Carole Celeste",
			"Laxalt, Michelle Therese",
			"Lazarus, Jeffrey L",
			"Lazer, Jessica J.",
			"Le, Thao ",
			"Leach, Natalie E",
			"Lecalvez, Eric J.",
			"Lecroix, Brian Chadwick",
			"Lecroix, Rebecca Hill",
			"Lederberg, Amy R.",
			"Lee, Andrew William",
			"Lee, Benjamin Bowden",
			"Lee, Beverly A",
			"Lee, Gary L",
			"Lee, Hakyoon ",
			"Lee, Heeseung ",
			"Lee, I-Hsien ",
			"Lee, Jeonghyun ",
			"Lee, Jiwon ",
			"Lee, Nian Lim ",
			"Lee, Nuni ",
			"Lee, Raniqua S.",
			"Lee, Sarah Margaret",
			"Lee, Taneisha Michelle",
			"Leide, Josephine Mabel",
			"Leighton, Leslie Steven",
			"Lemaster, Liane D.",
			"Lemieux, Anthony Francis",
			"Lemons-Smith, Shonda ",
			"Lennon, Christina Early",
			"Lentz, Jennifer Johnson Camp",
			"Leonardo, Gisabel ",
			"Lepine, Sebastien ",
			"Leroux, Audrey Josee",
			"Lessa Rodrigues, Luciana ",
			"Lester, Cynthia Yvette",
			"Lester, Tameka Eileen",
			"Levacy, Megan Renee",
			"Leventhal, Amy ",
			"Levinson, Jane C",
			"Lewin, Micah T",
			"Lewis, Charles Mcarthur",
			"Lewis, Gabriella ",
			"Lewis, Gregory Burr",
			"Lewis, Phillip William",
			"Lewkowicz, Marjorie L.",
			"Li, Chunying ",
			"Li, Hongli ",
			"Li, Ji ",
			"Li, Jian Dong",
			"Li, Shuai ",
			"Li, Wei ",
			"Li, Yingshu ",
			"Li, Zhongshan ",
			"Liang, Huaqing ",
			"Liang, Yan ",
			"Liddie-Hamilton, Bernice W.",
			"Lietz, Warren Carl",
			"Lifshey, Hollie ",
			"Light, Sharee Nicole",
			"Lightsey, Robert S.",
			"Ligon, Jan Howard",
			"Lill, Jeremy Brandon",
			"Lim, Nicole Cybil",
			"Lim, Yoonjeong ",
			"Lima, Ashley Chantelle",
			"Lima, Marcel Benetti de",
			"Lin, Yu-Kai ",
			"Lindberg, Kathryn Annette",
			"Lindemann, Stephanie A.",
			"Lindner, Rick ",
			"Lindquist, Travis C",
			"Lindsay, Jennifer Nadine",
			"Lindsay, Peter M.",
			"Lingenfelter, Allison C",
			"Lingle, Kristen Anne",
			"Lisby, Gregory C.",
			"Little, Ashley Jayne",
			"Little, Donya Renee",
			"Littrell, Jill L.",
			"Liu, Hui ",
			"Liu, Leigh Anne",
			"Liu, Songqi ",
			"Liu, Yang ",
			"Liu, Yen-Hung ",
			"Liu, Yuan ",
			"Liu, Zhi-Ren ",
			"Liverman, Remy ",
			"Livingston, Kelli A",
			"Llorente, Raul ",
			"Loch, Karen Diane",
			"Lochamy, Jonathan M",
			"Lockhart, Pavielle N",
			"Logan, Mary F",
			"Lomant, Susannah ",
			"Lombardo, Paul A.",
			"Lombardo, Thomas G",
			"Lonberger, George Edward",
			"Long, Jaletta Lynn",
			"Long, Kenneth A",
			"Long, William ",
			"Long, Yuan ",
			"Longman, Dihema R.",
			"Longobardi, Pamela ",
			"Lopez, Elizabeth S.",
			"Lorio, Anne Kilpatrick",
			"Lott, Marie Sumner",
			"Loux, Matthew D",
			"Loveall, Bradley S",
			"Lu, Albert Huei",
			"Lucas, Lauren Sudeall",
			"Luedtke, Cody Mullins",
			"Luke, Jessica L.",
			"Lund, Jacalyn L",
			"Luo, Ming ",
			"Luo, Ruiyan ",
			"Luvara, Angela Lynn",
			"Lyn, Rodney Shawn",
			"Lynch, Marcia Jean",
			"Lynch, Nicole Amy",
			"Ma, Han ",
			"Maamoun, Eman ",
			"Mabb, Angela Marie",
			"Mac, Linh Hoai",
			"Mack, John Nathan",
			"Madden, Charlene ",
			"Madden, Joshua Edward",
			"Madden, William Claude",
			"Maeng, Hyok Ju ",
			"Magee, Matthew James",
			"Mahr, Jeffrey Andrew",
			"Maier, Thomas Lee",
			"Maitra, Kinsuk Kumar",
			"Majerczyk, Michael John",
			"Major, Margaret H",
			"Makosky, John D",
			"Malamud, Randy ",
			"Malcolm, Sandra Gail",
			"Malcom, Julian Kenneth",
			"Malhotra, Charoo ",
			"Malinconico, Scott M",
			"Malone, Meagan E",
			"Manandhar, Kebina ",
			"Mandric, Igor ",
			"Mangum, Kyle Douglas",
			"Mani, Ramesh Ganapathi",
			"Mann, William Paul",
			"Manne-Nicholas, Emily Rachel",
			"Manning, Dexter Keith",
			"Manning, Karis T.",
			"Manole, Rusandica ",
			"Mansfield, Nancy R.",
			"Mansion, Kimbeni Harris",
			"Manson, Deborah Kay",
			"Manson, Steven T.",
			"Many, Joyce E.",
			"Marcovitch, Robert Peter",
			"Marcus, Jessica Ann",
			"Margulieux, Lauren Elizabeth",
			"Mariani, Victoria ",
			"Marinelli, Nicholas Thomas",
			"Markl, Christopher James",
			"Marlin, Jeffrey Arno",
			"Marrone, Stephen ",
			"Marsh, Leslie Louise",
			"Marshall, Amani Thomas",
			"Marshall, Daniel Eugene",
			"Marshall, John Travis",
			"Martens, Petrus Cornelis",
			"Martin, James Francis",
			"Martin, John C.",
			"Martin, Joshua L",
			"Martin, Lee Alan",
			"Martin, Melondy Pritchard",
			"Martin, Samantha D",
			"Martinez, Melissa ",
			"Martinkus, Caitlin ",
			"Marton, James H.",
			"Maruping, Likoebe Mohau",
			"Marvil, Charles E.",
			"Mason, Erin Chase McCarty",
			"Mason, John Lymon",
			"Mason, Mary Katherine",
			"Masoudi, Atena ",
			"Massie, Clarence W.",
			"Massignan, Virginia ",
			"Masyn, Katherine Elizabeth",
			"Matara kankanamge, Indika Senevirathna",
			"Matherne, Brett P.",
			"Mathiassen, Lars ",
			"Mathis, Kenneth A.",
			"Mathis, Rollin ",
			"Mativo, Vivian Ann Vankai",
			"Matteson, Zachary J",
			"Matthews, Lisa A",
			"Matthews, Valerie ",
			"Mattingly, Basil H.",
			"Mattson, Mary Frances",
			"Maune, Jeremy D",
			"Mauney, Clare ",
			"Maxwell, Kori Lloyd Hugh",
			"Maxwell, Robert Allan",
			"Maxwell, Tania ",
			"May, Frank Patrick",
			"May, Laura A.",
			"Mayambala, Christine S",
			"Mayberry, Robert Gene",
			"Mayfield, Kellie ",
			"Mazzotta, Mizuki ",
			"McArthur, Shirley A.",
			"Mcbride, Frederick Glenn",
			"Mccants, Jennifer Barnes",
			"McClymond, Kathryn ",
			"McComb, Francis William",
			"Mccool, Sarah Anne",
			"McCoy, Jennifer Lynn",
			"Mccoy, Ryan E",
			"McCrory, Victor Keith",
			"Mccrosky, Rachael Marie Caire",
			"McDonald, Christen Lyndsey",
			"McDowell, Robin John",
			"McDowell, Yvonne P.",
			"Mcelhannon, Tamara ",
			"McFarland, Mark John",
			"McGaw, Simone Elesha",
			"Mcgee, Kevin James",
			"McGehee, Glynn Milton",
			"Mcgill, Lynn B",
			"McGimsey, Ben Quiller",
			"Mcginnis, Diana B",
			"Mcglone, Jon V",
			"McGlothen, Tanisha ",
			"Mcgowan, Andrew J.",
			"McGrail, Ewa ",
			"McGuire, Mara R",
			"Mchaney, Pearl A.",
			"Mckee, Laura Gale",
			"Mckeown, Debra ",
			"McKinley, Robert Nicholas",
			"Mckinney, Louise Alayne",
			"Mckinney, Tracy C.",
			"Mcknight, Jimmie Rozell",
			"McLean, Ephraim Rankin",
			"Mclean, Gregory S.",
			"Mcleighton, Steven W.",
			"McLendon, Alton Ann",
			"Mcleod, Melissa K.",
			"Mcmillian, John Campbell",
			"Mcnair, Kerry Viondie",
			"Mcnamara, Kenneth B",
			"Mcnamara, Marissa Simone",
			"McNary, Tiffany Bennett",
			"McNease, Alicia Genell",
			"McPherson, Craig S",
			"Mctighe, Adam Jordan",
			"Meade, Joy Elizabeth",
			"Meadows, Leslie Julianna",
			"Meguiar, Pamela Cecilia",
			"Melnyk, Andrii ",
			"Menzel, Charles R.",
			"Mercier- De Shon, L. Michelle",
			"Merlin, Didier ",
			"Merritt, Necole J",
			"Merriweather, Kristi Bernann",
			"Messinger, Michael David",
			"Metcalfe, Douglas James",
			"Meyer, Brian Kevin",
			"Meyers, Barbara ",
			"Meyers, Joel ",
			"Meyers, Laura Elizabeth",
			"Meyers, Marian Joanne",
			"meza, Ana Carolina",
			"Middleton, Gregory Lamont",
			"Milam, Brent Alexander",
			"Milbrandt, Melody S.",
			"Miles, Edward W.",
			"Miletti, Luis A",
			"Milich, Paul S.",
			"Miller, Benjamin Joshua",
			"Miller, Hugh Richard",
			"Miller, Jennifer ",
			"Miller, Jon Michael",
			"Miller, Kari Holloway",
			"Miller, Ronald Clay",
			"Miller, Stevan Anthony",
			"Miller, Valerie ",
			"Milligan, Richard A",
			"Milner, John James",
			"Min, Xiaoyi ",
			"Mingo, Chivon A.",
			"Minick, Mary Ptlene",
			"Minter, Kendall A.",
			"Minyard, Karen Jean",
			"Minz, Christopher Michael",
			"Mishra, Abhay Nath",
			"Mitchell, Michael G",
			"Mitchell, Scott Alan",
			"Mitchell, Stacey M.",
			"Mitri, Souraya Mansour",
			"Mo, Huanbiao ",
			"Mobley, Lee Rivers",
			"Molette, Hannah ",
			"Molkov, Yaroslav Igorevich",
			"Mondecar, Mercedes C.",
			"Monlouis, Isabelle Nathalie",
			"Montague, Doralee ",
			"Montanera, Daniel ",
			"Montiel, Mariana ",
			"Moon, David Turner",
			"Moon Jr, James Robert",
			"Moore, Bernard Anthony",
			"Moore, Brenda Dorothy",
			"Moore, Gregory Martin",
			"Moore, Harriet Michelle",
			"Moore, James Alfred",
			"Moore, Josh David",
			"Moore, Marisa Chovan",
			"Moore, Robert E.",
			"Mooring, Suazette Reid",
			"Moosavi Motlaghian, Seyedeh Sara ",
			"Moradkhani Roshandeh, Arash ",
			"Morales, Jose C",
			"Morand Perrault, Louis ",
			"Morelli, Kimberly Meyer",
			"Moreno, Oscar H.",
			"Morgan, Andrea Scott",
			"Morgan, Don Michael",
			"Morgan, Jennifer Craft",
			"Morrey, Erin Lee Gallagher",
			"Morrier, Michael Joseph",
			"Morris, Claudia Vargas",
			"Morris, Jamae Fontain",
			"Morris, Robert D.",
			"Morris, Vangelia Andrea",
			"Morrison, Caren Myers",
			"Morrison, Jeffrey S",
			"Morrison, Reynolds Arthur",
			"Morrison, Stephen Dana",
			"Moshefi, Nina ",
			"Mosier, Phillip W",
			"Moss, John A.",
			"Moss, Sheryl Cowart",
			"Moss, Shondrika Lanise",
			"Moss, Stefan ",
			"Mostafa, Tamanna ",
			"Mote, Patricia T",
			"Moulson, Magdalena ",
			"Moultrie, Monique Nicole",
			"Mousa, Heather Ann",
			"Mouse, Mickey ",
			"Muhammad, Gholnecsar E.",
			"Muhammad, Tiy-E ",
			"Muiny, Somaya ",
			"Mullins, Linda S",
			"Mulvihill, Patrick James",
			"Muncy, Alice Marie",
			"Murovitz, Mark I",
			"Murphy, Anne Z",
			"Murphy, Anthony Craig",
			"Murphy, Jennifer Ellen",
			"Murphy, John M.",
			"Murphy, Sean E.",
			"Murphy, Thomas Matthew",
			"Murray, Gregory K",
			"Murray, Robert B",
			"Murray, Scott ",
			"Musante, Lawrence Duilio",
			"Mussa, Awad A. Younis",
			"Mutanyatta-Comar, Joan ",
			"Mvilongo, Anselme Blaise",
			"Nadri, Ghulam Ahmad",
			"Nahmias, Edward Andre",
			"Naim, S. Rashid",
			"Namayandeh, Alireza ",
			"Napper, Sarah Lashone",
			"Nargundkar, Satish V.",
			"Nash, Rodney James",
			"Nathan, Siva ",
			"Nattiel, Adreanna D",
			"Navarro-Eisenstein, Angela Maria",
			"Nduwimana, Alexis ",
			"Neal, Brennan Rudy",
			"Neal, Corey L",
			"Neculae, Andreea Roxana",
			"Nelson, Katherine S.",
			"Nelson, Michael R",
			"Nelson, Michelle Alyson",
			"Nelson, Robert B",
			"Nelson, Veatrice C.",
			"Nennig, Peter Ronald",
			"Neumark, Gerald Michael",
			"Newman, Timothy Jay",
			"Newton, Mark Lincoln",
			"Nguimkeu, Nguedia Pierre",
			"Nguyen, Tran Minh",
			"Nichols, William J",
			"Nicholson, Nancy Lee",
			"Nicholson, Terry J.",
			"Nickels, Neale Canter",
			"Nifadkar, Sushil Shyam",
			"Nixon, Roy A",
			"Noble, Mark Daniel",
			"Noel, Stuart D.",
			"Nogueira, Ricardo ",
			"Nomura, Glenn S",
			"Nooks, Alison Nicole",
			"Norgaard, Martin ",
			"Normandin, Joseph Jeremy",
			"Norton, Laura Emma",
			"Norwood, Romney ",
			"Nourizadeh, Sherry Kate",
			"Novokshanova, Eugenia ",
			"Nucci, Anita Marie",
			"Nusnbaum, Matthew ",
			"Nwosu, Nonye ",
			"O, Seunghae Grace ",
			"Oakley, Deirdre Ann",
			"Oates, Lalita U",
			"O'Bradovich, Mary Emily",
			"O'Brien, Emily Lemaster",
			"O'Bryant, Julie Walter",
			"Ocampo, Hernan ",
			"O'Connor, Laurie Thompson",
			"Offutt, Heather M",
			"Ogletree, August Elena",
			"Oguntebi, Zacchaeus Kunle",
			"Oh, Jeong-ha ",
			"Oh, Thomas Jeongtaek",
			"Okafor, Martin O",
			"OKane, John Francis",
			"Okeefe, Timothy S",
			"Okoh, Frederick Ifenwa",
			"Okoro, Gregory I",
			"Okosun, Solomon I",
			"Olive, Jennifer Nicole",
			"Oliver, Justin J",
			"Oliver, Kimberly B.",
			"Olowofoyeku, Olusegun O",
			"Olufemi, Gene Ezra",
			"Onyekwuluje, Juanita Marie",
			"Oommen, Kavita Sarah",
			"Ori, Peter F.",
			"Orkin Emmanuel, Lisa Dawn",
			"Orr, Janet ",
			"Orr, Jonathan Joseph",
			"Orr, Kathryn Anne",
			"Ortgies-Young, Tamra Susan",
			"Osakwe, Odilia Nwadiche",
			"Osan, Remus Mihai",
			"Osborn, Jodi Lynn",
			"Osborne, Lynda Lee",
			"Oshima, Takako ",
			"Otis, Jeffrey Scott",
			"O'Toole, Jason Steven",
			"Ouattara, Gnimbin Albert",
			"Oyenuga, Amy Sade",
			"Ozcaliskan, Seyda ",
			"Ozcan, Ozan ",
			"Pabis, George ",
			"Page, Sandra ",
			"Pai Daschke, Carmen Bianca Rawls",
			"Palizgir, Maryam ",
			"Palladi, Rhonda S.",
			"Pallas, Sarah L.",
			"Palmer, Michael D",
			"Palmiter, Margaret Lee",
			"Pan, Yi ",
			"Pangle, Luke Aaron",
			"Papavasiliou, Faidra ",
			"Paquin, Melissa Ann",
			"Parent, Marise Beverley",
			"Parilla, Jessica Marie",
			"Park, Jee Hye ",
			"Park, Seyoung ",
			"Parker, Jeffrey Robert",
			"Parker, Phyllis Lucille",
			"Parker-Shockley, Allison Lyons",
			"Parks, Austin Fields",
			"Parks, Samantha Terris",
			"Parrin, Austin ",
			"Parrott, Dominic J.",
			"Parsons, Patrick Raymond",
			"Parsons, Sheryl Renee",
			"Partridge, Kathleen S.",
			"Parvatiyar, Divya ",
			"Pascavage, Darren John",
			"Paschal, Daniel C",
			"Paschal, Sarah Davis",
			"Pasciuti, Daniel Steven",
			"Pascoe, Keith O.",
			"Patel, Hersheda ",
			"Patel, Punyapriya ",
			"Paterek, Jolanta Teresa",
			"Patico, Jennifer J.",
			"Patonay, Gabor ",
			"Patrick, Carlianne ",
			"Patrum, Christine Mary",
			"Patterson, DaShaunda Shenell",
			"Patterson, Hazelyn Mamette",
			"Patterson, Joe S",
			"Patterson, Nikita D.",
			"Pattillo, Linda L",
			"Patton-Terry, Nicole Sandi",
			"Patwardhan, Pallavee Chandrakant",
			"Paul, Claire Knob",
			"Paul, Maria Leema-Rose",
			"Paule, David Marvin",
			"Pauley, Alexandra Carter",
			"Pavao, Carlos A.O.",
			"Paxton-Wilson, Nancy ",
			"Payne, Erica L.",
			"Peace, Carley S",
			"Pearlman, Susan Rebecca",
			"Pearson, Nicole Hollie",
			"Pechacek, Terry Frank",
			"Peck, Laurence Freeman",
			"Peck, Zachary D",
			"Pedeva-Fazlic, Desislava Kostadinova",
			"Peiffer, Jerri Ann",
			"Peitso-Holbrook, Teri Jill",
			"Pelts, Bobby Ellis",
			"Pelzom, Yeshey ",
			"Pendarvis, Denise Threet",
			"Pendergast, Meghan Lane",
			"Peng, Jinwei ",
			"Peng, Liang ",
			"Penniman, Andrew J",
			"Pennington, Donna Ermellene Wroble",
			"Penumetcha, Vivekananda ",
			"Peppers, Bradley James",
			"Peragine, Joseph P.",
			"Peraza, Rene ",
			"Perdios, Stelios Vasilis",
			"Perera, Unil A.",
			"Perilla, Julia L.",
			"Perkins, Catherine Ann",
			"Perry, Colleen M.",
			"Perry, Joseph B.",
			"Perry, Katherine Denise",
			"Petersen-Frey, Pamela Susan",
			"Peterson, Lauren Michelle",
			"Petroni, Keith Mario",
			"Petrulis, Aras T.",
			"Pfeifer, Neil Grant",
			"Philip, Angela Davis",
			"Phillips, Alice Glenn",
			"Phillips, Chester Bryant",
			"Phillips, Ronald L",
			"Pierce, Alice Eiko",
			"Pierce, George E.",
			"Pihera, Corey P",
			"Pilling, Bruce K.",
			"Pimentel-Alarcon, Daniel Leonardo",
			"Pine, Ryan E",
			"Piper, Stephanie Vogler",
			"Pitchford, Timothy Ray",
			"Pittard, Elizabeth Ann",
			"Pitts, Brenda G.",
			"Pizzato, John Luke",
			"Plemmons, Alicia Morgan",
			"Plemper, Richard Karl",
			"Plitnick, Katherine Rose",
			"Podolski, Carolyn Robinson",
			"Poe, Janita Lorraine",
			"Poisson, Donetta Kay",
			"Poister, Theodore H.",
			"Poley, Jared C.",
			"Polovich, Martha ",
			"Ponder, Bentley Dwayne",
			"Pons, Victor Roberto",
			"Poole, Therese Marie",
			"Poon, Gregory Man Kai",
			"Popova, Lyudmila ",
			"Popowski, Sarah S.",
			"Porto, Paula D",
			"Poteat, Jerry Louis",
			"Poulos, Jason Nicholas",
			"Powell, Adeya Shontelle",
			"Powell, Bonnie Oliver",
			"Powell, Rachel Maria",
			"Powell, Virginia Catherine",
			"Prasad, Sushil K.",
			"Pratt, Jane Lillian",
			"Prechter, Ryan Buchanan",
			"Preddie, Aldene R",
			"Prewitt, Neill D",
			"Price, William D",
			"Prime, Penelope Benson",
			"Pritchett, Reagan Griggs",
			"Privett, Joshua M",
			"Prizer, Lindsay Penny",
			"Prudchenko, Slava M",
			"Pruden, Meredith L.",
			"Pruvenok, Robert Andrew",
			"Pugh, Myrna Kayleen",
			"Pullman, George L.",
			"Puranik, Cynthia S.",
			"Puscas, Richard O",
			"Putt, Aaron Kagan",
			"Qi, Xin ",
			"Qin, Gengsheng ",
			"Quearry, Jayson William",
			"Qureshi, Aneela Laurel",
			"Rabinovitch, Gilad ",
			"Radford, Mary F.",
			"Radnoczi, Michael Shane",
			"Raengo, Alessandra ",
			"Raghavan, Deepak ",
			"Rahimzadeh, Golnoush ",
			"Rahman, Husneara ",
			"Rahman, Tahmina ",
			"Rai, Arun ",
			"Rai, Harpreet Kaur",
			"Rainey, Jaclyn ",
			"Rainwater, Cherie Williams",
			"Rajiva, Jay ",
			"Rallapalli, Murthy V.",
			"Ramesh, Balasubramaniam ",
			"Ramos, Mary Dioise Mata",
			"Ramsey-White, Kim Renee",
			"Ramzy, Rasha I.",
			"Rand, Sebastian Gerard",
			"Rankin, Nicolas Ramon",
			"Ransom, Telmeko ",
			"Ransopher, Tad D.",
			"Rashid, Fontina Louise",
			"Ravita, Tracienne ",
			"Rawdon, Christopher Lawrence",
			"Ray, GiGi Bhaswati",
			"Raynor, Chavis Terrill",
			"Reati, Fernando O.",
			"Reber, Amy Jean Horner",
			"Reddick, Erin Anwar",
			"Reddick, Mark Gibson",
			"Redding, Kristi Carver",
			"Reddivari, Sahithya ",
			"Redic, Richard Charles",
			"Mr Reed, Joseph Lamont",
			"Reed, Mark D.",
			"Reed, Nia Malika",
			"Reese, Gregory Murray",
			"Refsnes, Jennifer Lynn",
			"Rehder, Vincent ",
			"Reichardt, Joanne Delavan",
			"Reid, Thomas Devin",
			"Reidy, Dennis E",
			"Reilly, Barbara Ann",
			"Reimann, Kim D.",
			"Reinhardt, Cody Karl",
			"Reinkemeyer, Joe W.",
			"Reiter, John David",
			"Reitzes, Donald C.",
			"Ren, Haoshan ",
			"Render, Marilyn Dabney",
			"Renken, Maggie Dehart",
			"Repnikova, Maria ",
			"Resh, Julie Anne",
			"Restivo, Angelo ",
			"Reynolds, Dexter Eugene",
			"Reynolds, Douglas R.",
			"Reynolds, Newburn Charles",
			"Rhodes, Gwendolyn Bernitha",
			"Rhymes, Marcus Henson",
			"Rice, Jerry Cheston",
			"Rice, Kenneth George",
			"Rice, Robert Eugene",
			"Richey, Sean Eric",
			"Richmond, Susan E",
			"Richtarik, Marilynn J.",
			"Rickets, Ilse Yvonne",
			"Rider, Mark W.",
			"Rigdon, Edward Eugene",
			"Riggenbach, Chris Michael",
			"Riggs, Jack C",
			"Rigney, Robert Mark",
			"Rioja, Felix Korman",
			"Rivero, Rene David",
			"Rizzo, R. L.",
			"Robbins, Chandan Morris",
			"Robbins, Shana Leigh",
			"Roberson, Karen ",
			"Roberson, Nicholas G",
			"Roberts, James H.",
			"Roberts, John William",
			"Roberts, Makeda Bernice",
			"Robertson, Barbara Smith",
			"Robertson, Sally J",
			"Robilotto, Thomas Jonathan",
			"Robin, Daniel Benjamin",
			"Robinson, Ann Marie",
			"Robinson, Cheryl Ann",
			"Robinson, Montez K.",
			"Robinson, Richard Wayne",
			"Robinson, Robert Christopher",
			"Robinson, Selma ",
			"Robinson, William N.",
			"Roch, Christine Heike",
			"Rochaix, Fernando ",
			"Rockward, Michelle Lori",
			"Rockwell, Ashley Marie",
			"Rodgers, Edmund William",
			"Rodrigo, Victoria ",
			"Rodriguez, Amy Denise",
			"Roemer-Weyhofen, Ute ",
			"Roessle, Peter A",
			"Rogers, Amanda B",
			"Rogers, Jennifer A",
			"Rogol, Natalie Carol",
			"Rohleder, Peter Alexander",
			"Rolinson, Mary Gambrell",
			"Roller, Olivia M.",
			"Rollins, Amy ",
			"Romski, Mary Ann",
			"Ronkin, Emily ",
			"Rosbruck, Michele Lee",
			"Rose, Jessica Alcorn",
			"Rose, Nicolette Olivia",
			"Roseberry, Aaron Gregory",
			"Rosen, Theodore John",
			"Rosenfelt, Jennifer Renee",
			"Ross, Glenwood ",
			"Ross, Sheila Ann",
			"Roth, Wendy Ann-Swenson",
			"Rothenberg, Richard Bernard",
			"Roudane, Matthew C.",
			"Rouhani, Behnaz ",
			"Rowberry, Ryan Max",
			"Rowe, Cora Layne Mills",
			"Roy, Engrid ",
			"Rozier, Kelvin Eugene",
			"Rubenstein, Ross H.",
			"Ruccio, Kristen Anna",
			"Rucks, Paula Jean",
			"Rudolph, Nathan Todd",
			"Rudy, Stephen James",
			"Ruel, Erin E.",
			"Ruff, Craig K.",
			"Ruprecht, Louis Arthur",
			"Rusodimos, Iason ",
			"Russell, Benjamin T",
			"Russell, John Clyde",
			"Russell, Joshua T",
			"Rutledge, Lindsey Rene'",
			"Ryan, Maura M",
			"Saadut, Raihana ",
			"Sabol, William Joseph",
			"Saboo, Alok R",
			"Sabree, Haazim S",
			"Sadhasivan, Mohan ",
			"Sadiraj, Vjollca ",
			"Sadri, Saeideh L",
			"Safer, Julia Wynn",
			"Saffarizadeh, Kambiz ",
			"Saffold, Katrina Deaann",
			"Saghaeiannejad Esfahani, Sayed Hossein ",
			"Sain, Lloyd ",
			"Saint, Michael Joseph",
			"Saint Ours, Nathan ",
			"Saito, Natsu S.",
			"Sakuta, Michael Wayne",
			"Salameh, Mohd A",
			"Salazar, Laura F.",
			"Salcedo, Veronica B",
			"Salters, Marlena Middlebrook",
			"Samaddar, Subhashish ",
			"Samson, Lindsay Grant",
			"Samuel, Donald Franklin",
			"Samuels, Steven ",
			"Sanders, Lowell ",
			"Sandlin, Erin W",
			"Sandmeier, Miglena Ivanova",
			"Sandy, Anna M.",
			"Sannigrahi, Biswajit ",
			"Sarabia, Stefani ",
			"Sarac, Ioana Magoalena",
			"Sarkar, Sutandra ",
			"Sarker, Krishanu ",
			"Sarnat, Ann Miriam",
			"Sarsour, Murad G",
			"Sass, Tim Roger",
			"Satter, Faysal I",
			"Sauers, Nicholas John",
			"Saunders, Steven Clayton",
			"Sawyer, Mary Rachel",
			"Saye, Eric Michael",
			"Scales, Stacey Dion",
			"Scarantino, Andrea ",
			"Schaefer, Donald David",
			"Schafer, Nancy Jo",
			"Schatteman, Renee ",
			"Schiffer, Sheldon Elias",
			"Schlig, Carmen ",
			"Schmidt, Manfred ",
			"Schmidt, Paul H.",
			"Schmitz, Kurt William",
			"Schober-Peterson, Debra L.",
			"Schock, Carlye A",
			"Schoene, Melissa P.",
			"Schorpp, Susanne ",
			"Schrepfer, Matthew Ryan",
			"Schroen, Charles B",
			"Schulte, Kimberly ",
			"Schwartz, Daniel J",
			"Schwartz, Renee Suzanne",
			"Schwarze, Lois Anne",
			"Scott, Charity ",
			"Scott, Damon M",
			"Scott, Debra ",
			"Scott, Jessica Armytage",
			"Scott, Joan Walker",
			"Scott, Lionel D.",
			"Searcy, Cynthia Schirmer",
			"Seelman, Kristie Lynn",
			"Seffrin, Mary Denning",
			"Segall, Eric J.",
			"Seidman, Amie Christine",
			"Sekhon, Nirej S.",
			"Self Brown, Shannon Renee",
			"Selwood, Jacob William",
			"Seoh, Hyuk Kyu",
			"Serpico, Anthony ",
			"Service, Angela Michelle",
			"Sevcik, Galen R.",
			"Sevcik, Rose Ann",
			"Sevigny, Eric Leo",
			"Sewani, Farzana S",
			"Sexton, Megan M.",
			"Seymour, Joseph L.",
			"Shackleford, Julie Ann",
			"Shah, Denish Harshadbhai",
			"Shahaf, Sharon ",
			"Shamsi, Shahab A.",
			"Shan, Shi Huh Samuel",
			"Shanholtzer, Sheryl ",
			"Shannon, Lisa Renee",
			"Shannonhouse, Laura Rosemary",
			"Shanteau, Janet Sawicki",
			"Shapero, Taylor Mclachlan",
			"Shapiro, Deborah ",
			"Shapiro, Michael Bruce",
			"Shen, Mo ",
			"Shen, Zhijun ",
			"Shepard, Jason Scott",
			"Shepard, Patience ",
			"Shephard-Massat, Sherry Michelle",
			"Sherman, Peggy B.",
			"Shi, Bei ",
			"Shi, Christine Marie",
			"Shi, Hang ",
			"Shi, Zhen ",
			"Shields, Rosemarie A.",
			"Shilnikov, Andrey ",
			"Shim, Jung P.",
			"Shimoyama, Delizzia Zena",
			"Shinholser, John Harlow",
			"Shobe, Kelly Fisher",
			"Shoffner, Mary B.",
			"Shore, Stephen Hammond",
			"Shortell, David Brian",
			"Shreckengost, Jacob Michael",
			"Shrikhande, Milind M.",
			"Shue, Tamara J",
			"Shuford, Charles Robert",
			"Siddula, Madhuri ",
			"Siegler, Jennifer Evelyn",
			"Siehlmann, Jillian Kay",
			"Siler, John Henderson",
			"Simanga, Michael Pili",
			"Simonds, Wendy S.",
			"Simony, Christopher S.",
			"Simpkins, Joshua J",
			"Sims, Ashia Renea",
			"Sims, Traci T.",
			"Simson, William Ronald",
			"Singleton, Louis Roosevelt",
			"Sinnott, Megan Jane",
			"Sisson, Richard Kimberly",
			"Sitvarin, Michael Ian",
			"Skaggs, Patrick Donald",
			"Skelton, Brooke Patterson",
			"Skipper, Tia ",
			"Skums, Pavel ",
			"Slovensky, Heather Kern",
			"Smartis, Craig S",
			"Smartt Gaither, Joann M",
			"Smeal, Lucia Nasuti",
			"Smirnova, Alexandra B.",
			"Smith, Angie Valencia",
			"Smith, Colin Keith",
			"Smith, Dequan M",
			"Smith, Donna Jo",
			"Smith, Gary Howard",
			"Smith, Gregory M.",
			"Smith, John David",
			"Smith, Kenneth R",
			"Smith, Kimberly D.",
			"Dr Smith, Rodney Reiko Yates",
			"Smith, Sherry Patricia",
			"Smith, Stephanie Zeyer",
			"Smith, Stephen Michael",
			"Smith III, Joseph Purser",
			"Smith Jr., Edward S",
			"Smolinski, Reiner ",
			"Snape, Jason James",
			"Snell, Debra Sydney",
			"Snoddy, Catherine E",
			"Snow, Malinda G.",
			"Snyder, Susan Marie",
			"Sobelson, Roy M.",
			"Socci, Robin R",
			"Sommer, John Paul",
			"Song, Chi-Sun Kay",
			"Soni, Anmol ",
			"Speckhals, Trent B.",
			"Spino, Michael Philip",
			"Spratling, Regena Gayle",
			"Spring, Amy Lynn",
			"Stafford, Richard Dobson",
			"Stair, Anne Catherine",
			"Stanford, Ruth Ann",
			"Stanko, Paul John",
			"Starrick, Amanda ",
			"Stauber, Christine Elizabeth",
			"Steffen, Charles G.",
			"Steigerwalt, Amy Lynn",
			"Steinau, Athertina Nannette",
			"Stephens, Corneill A.",
			"Stephens, Marissa Hewatt",
			"Sternberg, Maya Raquel",
			"Stevens, Cynthia M.",
			"Stevens, Douglas Edwin",
			"Steward, John A.",
			"Stewart, Ann Helen",
			"Stewart, Dion C",
			"Stewart, Larry Buster",
			"Stewart, Michael A.",
			"Stickney, Natalie Lane",
			"Stickney, Sean ",
			"Stigall, Jason C",
			"Stinson, David Wayne",
			"St. John, David E",
			"Stockman, Mark ",
			"Stockslager, Robyn ",
			"Stombler, Mindy ",
			"Stone, Adam P",
			"Stone, Michael K",
			"Storey, Nancy Catri",
			"Storey, Veda C.",
			"Strange-Soria, Luise E.",
			"Strauss, Kara Alison",
			"Strawser, Charla Elizabeth",
			"Streib, Gregory D.",
			"Strickler, Elizabeth S.",
			"Stringer, Christopher Bayard",
			"Stroev, Mikhail ",
			"Stroeva, Elina ",
			"Strong, Michael Wade",
			"Strosnider, Courtney Leigh",
			"Strother, Dora ",
			"Strother, Robert ",
			"Stuart, Esther M",
			"Studebaker, Todd A.",
			"Sturgess, Anan Li",
			"Suarez, Tony ",
			"Sublett, Laroyce J",
			"Subotic, Jelena ",
			"Subramanian, Ajay R",
			"Sudan, Brenda Naimah",
			"Sugarman, Matthew L.",
			"Sullivan, Caroline Cecelia",
			"Sullivan, Jane W",
			"Sullivan, John Francis",
			"Summer, Saralyn E",
			"Summerill, Corinne Alethea Oriana",
			"Sumner, Andrew T.",
			"Sunderraman, Rajshekhar ",
			"Sussman, Linda Carolyn",
			"Suzuki, Sakiko ",
			"Swafford, Kristi Dawn",
			"Swahn, Monica Havisto",
			"Swanson, Peter B.",
			"Swars, Susan Lee",
			"Swarthout, James Todd",
			"Swartout, Ashlyn Gollehon",
			"Swartout, Kevin Michael",
			"Sweetser, Victor Eric",
			"Swenson, Kirk R",
			"Sylvester, Jonathan Blaylock",
			"Tai, Phang-Cheng ",
			"Talburt, Susan ",
			"Tanguay, Carla Lynn",
			"Tao, Xiaohong ",
			"Tapp, Susannah Naomi",
			"Tate, Lakeisha B.",
			"Taylor, Barbara E.",
			"Taylor, Beverley May",
			"Taylor, Brandon Richard",
			"Taylor, Brandyn Kyle",
			"Taylor, Jessica Lauren",
			"Taylor, Kenya Rashita",
			"Taylor, Nekeidra Yvette",
			"Taylor, Nicole Alicia",
			"Tchernis, Rusty ",
			"Teper, Douglas Clark",
			"Tepper, Kirstie J",
			"Terry, David D",
			"Thagard, Elaine Kirk",
			"Thakkar, Chintan Hemendrakumar",
			"Thalken, Constance J.",
			"Thielman, John Phillip",
			"Thomas, Christine D.",
			"Thomas, Clarice ",
			"Thomas, Dominique ",
			"Thomas, H. Calvin",
			"Thomas, Iris ",
			"Thomas, Jason Wesley",
			"Thomas, Jo Dobbs",
			"Thomas, John Clayton",
			"Thomas, Stephanie Short",
			"Thomas, Tami Wells",
			"Thomas, Tracy Elaine",
			"Thomas, Ursula C",
			"Thompson, A. Deon",
			"Thompson, Gina Renee",
			"Thompson, Matthew Paul",
			"Thompson, Nils Wilder",
			"Thompson, Robert Scott",
			"Thompson, Walter R.",
			"Thoms, Brian D.",
			"Thornton, Corliss Green",
			"Thornton, Harriet E.",
			"Thornton, Robert G",
			"Thornton, William Vann",
			"Thota, Jyotsna ",
			"Tice, Misty B.",
			"Tighe, Elizabeth Leslie",
			"Timmons, Christopher W.",
			"Timmons, Kelly Cahill",
			"Tims, W. Keith",
			"Timsina, Tirtha Prasad",
			"Tinker-Sachs, Gertrude ",
			"Todres, Jonathan ",
			"Tolley, Harry W",
			"Tolson, Claudette L",
			"Tomov, Elin Tomov",
			"Tone, Erin ",
			"Topalli, Volkan ",
			"Topping, Elizabeth A",
			"Torres, German M.",
			"Toula, Christopher Michael",
			"Tovrog, Benjamin Samuel",
			"Townsend, Kyle Michael",
			"Townsend, Stephanie Tia",
			"Trahan, Joseph V.",
			"Tran, Thien Ba Duc",
			"Trani, Manuela ",
			"Trask, Jeffrey Lee",
			"Travis, Regina Steele",
			"Tredway, Thomas S",
			"Tremblay-Boire, Joannie ",
			"Trivette, Mark E.",
			"Truex, Duane P.",
			"Trugman, Catherine Wright",
			"Trulock, Todd Sutton",
			"Truscott, Diane Marie",
			"Truscott, Stephen D.",
			"Truss, Cedric ",
			"Trusty, Jennifer Lynn",
			"Tsai, Liang-Ching ",
			"Tubbs, Jerri Lynn",
			"Tucker, Anne M.",
			"Tucker, Bryan Duane",
			"Tully, Erin ",
			"Turner, Chrisitan Brent",
			"Turner, Dennise Mickelle",
			"Turner, Jessica Ann",
			"Turner, Nicole K",
			"Turner-Livermore, Bethany Lynn",
			"Turner-Pugh, Pearl ",
			"Tusher, Chantal Poister",
			"Tussey, Ethan ",
			"Tutt, Tanesha Goldwire",
			"Tyagi, Ashutosh ",
			"Tyler Boucebci, Mary Elizabeth ",
			"Tywoniw, Rurik L",
			"Udell, Rachelle Sabrina",
			"Ueng, Yunn ",
			"Ukpabi, Ifeanyichukw U.",
			"Ulevich, Lisa Michelle",
			"Ullrich, Alexander David",
			"Ulrich, Paul N",
			"Umana, Enefiok ",
			"Umashankar, Nita ",
			"Umoja, Akinyele K.",
			"Umoja, Chinua Tyehimba",
			"Vahidnia, Hamid ",
			"Vainer, Sophie Michele",
			"Valley, Christopher R.",
			"Van Der Holst, Hendricus ",
			"Van Herik, Edward Richard",
			"Van Jelgerhuis, Daniel ",
			"Van Leeuwen, David Stewart Neil",
			"Van Norman, Ethan Richard",
			"Vanwulven, Tyler Benton",
			"Varadarajan, Deepa ",
			"Vargis, George N",
			"Vargis, Salli Vargis ",
			"Varjas, Kristen M.",
			"Varnes, Justin Andrew",
			"Varshney, Upkar ",
			"Vath, Margaret Hughes",
			"Vaughn, Linda Latimer",
			"Velasco, Cassandra Nicolle",
			"Venable, Alison Melina",
			"Vepraskas, Nancy Murphy",
			"Verhaal, Jeffrey Cameron",
			"Vermillion, Nicole Marie DeCorte",
			"Vernick, Gordon J.",
			"Vickery, William Grant",
			"Vidakovic, Draga ",
			"Villa, Brandi ",
			"Visaggi, Christy Corinne",
			"Vivas, Reyes Jose",
			"Vollmer, Niklas S.",
			"Volpert, Ariel Jaye",
			"Von Korff, Joshua Solomon",
			"Vonsteinhauer, Hans-Peter ",
			"Voss, Paul John",
			"Wade, Cory D",
			"Wagner, Nathan R",
			"Walcott, Carolyn B",
			"Waldbart, Adria ",
			"Walden, Tammy Bezona",
			"Walker, Barbara Dianne",
			"Walker, Eric Dane",
			"Wallace, Elizabeth Ann",
			"Wallace, Lynn Christina",
			"Wallace, Walter L.",
			"Wallen, Stacey V.",
			"Walls, Barrett ",
			"Walthall, Walter W.",
			"Wamsley, Richard Curtis",
			"Wanders, Desiree ",
			"Wang, Baozhong ",
			"Wang, Binghe ",
			"Wang, Danzhu ",
			"Wang, Gangli ",
			"Wang, Peng ",
			"Wang, Rui ",
			"Wang, Ruili ",
			"Wang, Siming L",
			"Wang, Xing ",
			"Wang, Yinying ",
			"Wang, Zhe ",
			"Ward, Brandon M",
			"Ward, Charmaine ",
			"Warner, Barbara D.",
			"Warren, Gordon ",
			"Warren, Randy Donald",
			"Washburn, David Alan",
			"Washington, Julie Ann",
			"Washington, Tanya Monique",
			"Watkins, Karen Yvonne",
			"Watson, Stephanie ",
			"Way, John Thomas",
			"Waymack, Matthew Parvin",
			"Weatherly, Monica Lee",
			"Weaver, Rebecca Elene",
			"Webb, Chequita Yolette",
			"Weber, Gerald Richard",
			"Weber, Irene ",
			"Weber, John J",
			"Weber, Robert F.",
			"Wedeman, Andrew ",
			"Weeks, Michael C.",
			"Wei, Guanhao ",
			"Weir, Joanne ",
			"Weiskopf, Daniel Aaron",
			"Welborn, Daniel Charles",
			"Welch, Shellie M Sims",
			"Wells, Charles Talley",
			"Wells, Neena Diane",
			"Welsh, Kaprice ",
			"Weltlich, Sharon White",
			"Wen, Pey-Shan ",
			"Wernecke, Christopher J",
			"Wertheimer, Mindy R.",
			"West, Christina A",
			"West, Elizabeth J.",
			"West, Nathaniel C.",
			"Westbrook, Charles J",
			"Westfall, Susan G",
			"Weston, Harold Alan",
			"Westrick, Kristen Pearson",
			"Wexler, Jack ",
			"Weyermann, Andrea Grace",
			"Wharton, Robin Selece",
			"Whatley, Jillian K",
			"Wheel-Carter, Karen Denise",
			"Wheeler, John Noel",
			"Whisenhunt, Benjamin Louis",
			"Whitaker, Daniel James",
			"White, Cassandra ",
			"White, Christina Lynn",
			"White, Dennis L.",
			"White, Diana ",
			"White, Marta S.",
			"White, Michael A.",
			"White, Michele Barksdale",
			"White, Russel Joseph",
			"Whitley, Deborah M.",
			"Whitney, Carrie L.",
			"Whittemore, John F.",
			"Whitten, Amy Janette",
			"Widman, Tracy A.",
			"Wiggins, Dana C.",
			"Wilczynski, Walter ",
			"Wilder, Seth Adam",
			"Wilding, Nicholas ",
			"Wiley, Katherine Keehn",
			"Wilhelm, James Christopher",
			"Wilk, Eric Michael",
			"Wilkin, Holley Ann",
			"Wilkins, Rhonda D.",
			"Willey, Susan L.",
			"Williams, Allison Douglass",
			"Williams, Ann Erin",
			"Williams, April Dawn",
			"Williams, Brian ",
			"Williams, Frank L.",
			"Williams, Jack Frederick",
			"Williams, James Robert",
			"Williams, Jeffrey Albert",
			"Williams, Jessica M",
			"Williams, Margo Hall",
			"Williams, Patricia Marie",
			"Williams, Rhina Maria Fernandes",
			"Williams, Shawn L",
			"Williams, Tammie Renea",
			"Williams, Tanya Latrice",
			"Williams-Jones, Karen Michelle",
			"Williamson, Rebecca A.",
			"Williard, Jess M",
			"Willis, Shayla R",
			"Wilson, Adam Christopher",
			"Wilson, Christyl Yensuahte-Ardina",
			"Wilson, Clark ",
			"Wilson, Eric Entrican",
			"Wilson, Jiha Moon",
			"Wilson, Joanna ",
			"Wilson, John William",
			"Wilson, Kathryn E",
			"Wilson, Megan Lee",
			"Wilson, Stacy M",
			"Wilson, William D.",
			"Wilson Matthews, Ramona ",
			"Wingert, David W.",
			"Winking, Matthew M",
			"Winkler, Carol Kay",
			"Winston, Jason Harlow",
			"Wise, Julia Beth",
			"Wiseman, Patrick ",
			"Wisner, Linell Buell",
			"Wojnowski, David ",
			"Wolf, Leslie E.",
			"Wolfe, Kateland Leigh",
			"Wong, Brett James",
			"Wood, Barry William",
			"Woodacre, Melissa Anne",
			"Woodcock, Ramsi ",
			"Woodfill, Brent Kerry Skoy",
			"Woodrum, Robert H.",
			"Woods, Kalisha V",
			"Woods, Meghan P",
			"Woods, Ryan T.",
			"Worozbyt, Theodore S.",
			"Wrenn, Diana Christine",
			"Wright, Allison Elizabeth",
			"Wright, Christa Young",
			"Wright, Drew Mitchell",
			"Wright, Eric Reaney",
			"Wright, Michelle ",
			"Wright, Richard Thomas",
			"Wu, Jianhua ",
			"Wu, Yubao ",
			"Wyczalkowski, Christopher ",
			"Xia, Yusen ",
			"Xiao, Xueli ",
			"Xie, Zhonglin ",
			"Xin, Yao ",
			"Xu, Bin ",
			"Xu, Hao ",
			"Xu, Yongsheng ",
			"Xue, Bingzhong ",
			"Xue, Ling ",
			"Yan, Zhisheng ",
			"Yang, Alan Thorngeng",
			"Yang, Baozhong ",
			"Yang, De ",
			"Yang, Feng ",
			"Yang, Hae Sung ",
			"Yang, Jenny J.",
			"Yang, Su ",
			"Yang, Xiaohui ",
			"Yang, Yukun ",
			"Yankey, Barbara Araba",
			"Yao, Senmei ",
			"Yao, Wenxiong ",
			"Yao, Yongwei ",
			"Yarn, Douglas H.",
			"Yates, Michael Charles",
			"Ye, Xiaojing ",
			"Yenerall, David Lawrence",
			"Yeomans, Kevin D",
			"Yilmaz, Selahattin ",
			"Yin, Jun ",
			"Yin, Liping ",
			"Young, Aaron Jamal",
			"Young, Bonnie J",
			"Young, Jeffrey Robert",
			"Young, Kenya Charvae",
			"Young, Stephen Paul",
			"Younkins, Allison Lee Gerson",
			"Yrigollen, Michelle ",
			"Yu, Liqing ",
			"Yu, Liyang ",
			"Yu, Meng ",
			"Yu, Xue ",
			"Yuce, Ahmet ",
			"Zagara, Marc A",
			"Zagara, Tina Marie",
			"Zagrodny, Christopher Michael",
			"Zayac, Marc S",
			"Zeigler, Essie Lynn",
			"Zelikovskiy, Aleksandra ",
			"Zellars, Malcolm ",
			"Zettler, Patricia J.",
			"Zhan, Heying Jenny",
			"Zhang, Chenyi ",
			"Zhang, Guoqiang P.",
			"Zhang, Hongmei ",
			"Zhang, Jing ",
			"Zhang, Yanqing ",
			"Zhang, Yimai ",
			"Zhao, Kai ",
			"Zhao, Yali ",
			"Zhao, Yi ",
			"Zhao, Yi ",
			"Zhao, Yi ",
			"Zhao, Yichuan ",
			"Zhdanov, Dmitry ",
			"Zheng, Danyang ",
			"Zhong, Changyong ",
			"Zhu, Chungeng ",
			"Zhu, Tiffany Ameline",
			"Zhu, Ying ",
			"Zimmerman, Ralph David",
			"Zisook, Karla Jean",
			"Zorland, Jennifer Lee",
			"Zoss, Michelle Leigh",
			"Zou, Ming-Hui ",
			"Zuk, Tanya Dolores");
	ObservableList<String> typeList = FXCollections.observableArrayList(
			"All", 
			"Arts Signature Experience", 
			"City Scholar", 
			"City Signature Experience",
			"Critical Thinking Thru Writing", 
			"Global Scholar", 
			"Global Signature Experience", 
			"Honors College",
			"Hybrid/Partially Online",
			"Online Section",
			"Professional Signature Exp",
			"Research Signature Experience",
			"Service Signature Experience",
			"Supplemental Instruction");
	ObservableList<String> hrList = FXCollections.observableArrayList(
			"01", 
			"02", 
			"03", 
			"04", 
			"05", 
			"06",
			"07",
			"08",
			"09",
			"10",
			"11",
			"12");
	ObservableList<String> minList = FXCollections.observableArrayList(
			"00", 
			"05", 
			"10", 
			"15", 
			"20", 
			"25", 
			"30",
			"35",
			"40",
			"45",
			"50",
			"55");
	ObservableList<String> perList = FXCollections.observableArrayList("am", "pm");
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		term.setItems(termList);
		degree.setItems(degList);
		subject.setItems(subList);
		campus.setItems(campList);
		partOfTerm.setItems(partList);
		instructor.setItems(instList);
		type.setItems(typeList);
		startHr.setItems(hrList);
		startMin.setItems(minList);
		startP.setItems(perList);
		endHr.setItems(hrList);
		endMin.setItems(minList);
		endP.setItems(perList);
	}

	public void comboChanged(ActionEvent event) {
		//myLabel.setText(combobox.getValue());
		
	}
}
