BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Major` (
	`Major ID`	INTEGER,
	`Major`	TEXT
);
INSERT INTO `Major` VALUES (1,'Accounting');
INSERT INTO `Major` VALUES (2,'Actuarial Science');
INSERT INTO `Major` VALUES (3,'African-American Studies');
INSERT INTO `Major` VALUES (4,'Art');
INSERT INTO `Major` VALUES (5,'Art History');
INSERT INTO `Major` VALUES (6,'Biology');
INSERT INTO `Major` VALUES (7,'Chemistry');
INSERT INTO `Major` VALUES (8,'Computer Information Systems');
INSERT INTO `Major` VALUES (9,'Computer Science');
INSERT INTO `Major` VALUES (10,'Criminal Justice');
INSERT INTO `Major` VALUES (11,'Economics');
INSERT INTO `Major` VALUES (12,'English');
INSERT INTO `Major` VALUES (13,'Environmental Science');
INSERT INTO `Major` VALUES (14,'Film and Media');
INSERT INTO `Major` VALUES (15,'Finance');
INSERT INTO `Major` VALUES (16,'Game Design and Development');
INSERT INTO `Major` VALUES (17,'Geosciences');
INSERT INTO `Major` VALUES (18,'History');
INSERT INTO `Major` VALUES (19,'Hospitality Administration');
INSERT INTO `Major` VALUES (20,'Human Learning and Development');
INSERT INTO `Major` VALUES (21,'International Business');
INSERT INTO `Major` VALUES (22,'Japanese');
INSERT INTO `Major` VALUES (23,'Journalism');
INSERT INTO `Major` VALUES (24,'Latin');
INSERT INTO `Major` VALUES (25,'Latin American Studies');
INSERT INTO `Major` VALUES (26,'Law and Society');
INSERT INTO `Major` VALUES (27,'Managerial Science');
INSERT INTO `Major` VALUES (28,'Marketing');
INSERT INTO `Major` VALUES (29,'Mathematics');
INSERT INTO `Major` VALUES (30,'Music');
INSERT INTO `Major` VALUES (31,'Neuroscience');
INSERT INTO `Major` VALUES (32,'Nursing');
INSERT INTO `Major` VALUES (33,'Philosophy');
INSERT INTO `Major` VALUES (34,'Political Science');
INSERT INTO `Major` VALUES (35,'Psychology');
INSERT INTO `Major` VALUES (36,'Real Estate');
INSERT INTO `Major` VALUES (37,'Risk Management and Insurance');
INSERT INTO `Major` VALUES (38,'Social Work');
INSERT INTO `Major` VALUES (39,'Sociology');
INSERT INTO `Major` VALUES (40,'Spanish');
INSERT INTO `Major` VALUES (41,'Special Education');
INSERT INTO `Major` VALUES (42,'Speech Communication');
INSERT INTO `Major` VALUES (43,'Theater');
INSERT INTO `Major` VALUES (44,'Women''s Gender and Sexuality Studies');
COMMIT;
